### ISSUE TITLE
Bug loading on CPU a model trained on GPU (Electra).

### ISSUE THREAD

**Issue by alvaroabascar** [ThilinaRajapakse/simpletransformers#1002]
**Describe the bug**
After pretraining an Electra model (with GPU), I tried to load it in a machine without GPU with the intention of saving the discriminator separately. I used the following code:

```python
import sys
from simpletransformers.language_modeling import LanguageModelingModel

model = LanguageModelingModel(
    "electra",
    sys.argv[1],
    use_cuda=False,
    args={"output_dir": sys.argv[2]}

model.save_discriminator()
```

Despite setting `use_cuda=False`, I get the following error (stack trace below):

```
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

**To Reproduce**

- Train an Electra with GPU.
- Try to load the model on a machine without GPU with the script above.

**Expected behavior**

- Model should be loaded without trying to use a GPU if `use_cuda=False` is set.

**Screenshots**

```
UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "scripts/save_discriminator.py", line 8, in <module>
    args={"output_dir": sys.argv[2], "use_cuda": False})
  File "/home/alvaro/.virtualenvs/electra/lib/python3.7/site-packages/simpletransformers/language_modeling/language_modeling_model.py", line 284, in __init__
    self.model.load_state_dict(torch.load(os.path.join(self.args.model_name, "pytorch_model.bin")))
  File "/home/alvaro/.virtualenvs/electra/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/alvaro/.virtualenvs/electra/lib/python3.7/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
  File "/home/alvaro/.virtualenvs/electra/lib/python3.7/site-packages/torch/serialization.py", line 845, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/alvaro/.virtualenvs/electra/lib/python3.7/site-packages/torch/serialization.py", line 834, in load_tensor
    loaded_storages[key] = restore_location(storage, location)
  File "/home/alvaro/.virtualenvs/electra/lib/python3.7/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/alvaro/.virtualenvs/electra/lib/python3.7/site-packages/torch/serialization.py", line 151, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/alvaro/.virtualenvs/electra/lib/python3.7/site-packages/torch/serialization.py", line 135, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - simpletransformers==0.60.9
 - torch==1.7.1

**Comment by alvaroabascar** [comment]
Possible fix here: https://github.com/ThilinaRajapakse/simpletransformers/pull/1003
