### ISSUE TITLE
Error importing T5Model from simpletransformers

### ISSUE THREAD

**Issue by tmbenhura** [ThilinaRajapakse/simpletransformers#1022]
**Describe the bug**
On a fresh installation of simpletransformers in a new environment, using pip, models cannot be imported T5Model

I tried --force reinstalling the package as prescribed in an older issue and this did not work. The transformers package installed is also the latest 4.3.3

**To Reproduce**
pip install pandas
pip install tqdm
pip install <pytorch-from-windows-specific-wheel>
pip install simpletransformers
----
In the python file:
from simpletransformers.t5 import T5Model, T5Args

Traceback (most recent call last):
  File "transformers.py", line 5, in <module>
    from simpletransformers.t5 import T5Model, T5Args
  File "...\lib\site-packages\simpletransformers\t5\__init__.py", line 2, in <module>
    from simpletransformers.t5.t5_model import T5Model
  File "...\lib\site-packages\simpletransformers\t5\t5_model.py", line 20, in <module>
    from transformers.models.t5 import T5Config, T5ForConditionalGeneration, T5Tokenizer
  File "test.py", line 5, in <module>
    from simpletransformers.t5 import T5Model, T5Args
ImportError: cannot import name 'T5Model' from 'simpletransformers.t5' (...\lib\site-packages\simpletransformers\t5\__init__.py)

**Expected behavior**
No error

**PIP Listing**
altair              4.1.0
argon2-cffi         20.1.0
astor               0.8.1
async-generator     1.10
attrs               20.3.0
backcall            0.2.0
base58              2.1.0
bleach              3.3.0
blinker             1.4
cachetools          4.2.1
certifi             2020.12.5
cffi                1.14.5
chardet             4.0.0
click               7.1.2
colorama            0.4.4
configparser        5.0.2
decorator           4.4.2
defusedxml          0.6.0
docker-pycreds      0.4.0
entrypoints         0.3
filelock            3.0.12
gitdb               4.0.5
GitPython           3.1.14
idna                2.10
importlib-metadata  3.7.0
ipykernel           5.5.0
ipython             7.21.0
ipython-genutils    0.2.0
ipywidgets          7.6.3
jedi                0.18.0
Jinja2              2.11.3
joblib              1.0.1
jsonschema          3.2.0
jupyter-client      6.1.11
jupyter-core        4.7.1
jupyterlab-pygments 0.1.2
jupyterlab-widgets  1.0.0
MarkupSafe          1.1.1
mistune             0.8.4
nbclient            0.5.3
nbconvert           6.0.7
nbformat            5.1.2
nest-asyncio        1.5.1
notebook            6.2.0
numpy               1.20.1
packaging           20.9
pandas              1.2.3
pandocfilters       1.4.3
parso               0.8.1
pathtools           0.1.2
pickleshare         0.7.5
Pillow              8.1.1
pip                 21.0.1
prometheus-client   0.9.0
promise             2.3
prompt-toolkit      3.0.16
protobuf            3.15.3
psutil              5.8.0
pyarrow             3.0.0
pycparser           2.20
pydeck              0.6.1
Pygments            2.8.0
pyparsing           2.4.7
pyrsistent          0.17.3
python-dateutil     2.8.1
pytz                2021.1
pywin32             300
pywinpty            0.5.7
PyYAML              5.4.1
pyzmq               22.0.3
regex               2020.11.13
requests            2.25.1
sacremoses          0.0.43
scikit-learn        0.24.1
scipy               1.6.1
Send2Trash          1.5.0
sentencepiece       0.1.95
sentry-sdk          1.0.0
seqeval             1.2.2
setuptools          54.0.0
shortuuid           1.0.1
simpletransformers  0.60.9
six                 1.15.0
smmap               3.0.5
streamlit           0.77.0
subprocess32        3.5.4
tensorboardX        2.1
terminado           0.9.2
testpath            0.4.4
threadpoolctl       2.1.0
tokenizers          0.10.1
toml                0.10.2
toolz               0.11.1
torch               1.7.1+cu110
tornado             6.1
tqdm                4.58.0
traitlets           5.0.5
transformers        4.3.3
typing-extensions   3.7.4.3
tzlocal             2.1
urllib3             1.26.3
validators          0.18.2
wandb               0.10.21
watchdog            2.0.2
wcwidth             0.2.5
webencodings        0.5.1
wheel               0.36.2
widgetsnbextension  3.5.1
zipp                3.4.0

**Desktop:**
 - Windows 10

**Additional context**
- Python 3.7.6

**Comment by tmbenhura** [comment]
On Ubuntu 20.4, with a fresh installation the problem persists but hints at a circular import:
Traceback (most recent call last):
  File "transformers.py", line 5, in <module>
    from simpletransformers.t5 import T5Model, T5Args
  File ".../lib/python3.8/site-packages/simpletransformers/t5/__init__.py", line 2, in <module>
    from simpletransformers.t5.t5_model import T5Model
  File ".../lib/python3.8/site-packages/simpletransformers/t5/t5_model.py", line 20, in <module>
    from transformers.models.t5 import T5Config, T5ForConditionalGeneration, T5Tokenizer
  File "test.py", line 5, in <module>
    from simpletransformers.t5 import T5Model, T5Args
ImportError: cannot import name 'T5Model' from partially initialized module 'simpletransformers.t5' (most likely due to a circular import) (.../lib/python3.8/site-packages/simpletransformers/t5/__init__.py)
