### ISSUE TITLE
Additional metric dont show.

### ISSUE THREAD

**Issue by juunnn** [ThilinaRajapakse/simpletransformers#1028]
Hi I just started to use a simple transformer for the seq2seq model and trying to copy an example that I found [here](https://simpletransformers.ai/docs/seq2seq-specifics/).  I tried to add an additional metric for my model since we use it for a different task. I tried the metric in the sample code, it works and gives the outputs as expected. But when I use the same config and metric, the metric doesn't show. It says something about pandas don't have the same length, but when I try with `model.eval_model` the dataset works fine and give the loss value.

This is the traceback that I got.
```
Some weights of BertLMHeadModel were not initialized from the model checkpoint at cahya/bert-base-indonesian-522M and are newly initialized: ['bert.encoder.layer.0.crossattention.self.query.weight', 'bert.encoder.layer.0.crossattention.self.query.bias', 'bert.encoder.layer.0.crossattention.self.key.weight', 'bert.encoder.layer.0.crossattention.self.key.bias', 'bert.encoder.layer.0.crossattention.self.value.weight', 'bert.encoder.layer.0.crossattention.self.value.bias', 'bert.encoder.layer.0.crossattention.output.dense.weight', 'bert.encoder.layer.0.crossattention.output.dense.bias', 'bert.encoder.layer.0.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.0.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.1.crossattention.self.query.weight', 'bert.encoder.layer.1.crossattention.self.query.bias', 'bert.encoder.layer.1.crossattention.self.key.weight', 'bert.encoder.layer.1.crossattention.self.key.bias', 'bert.encoder.layer.1.crossattention.self.value.weight', 'bert.encoder.layer.1.crossattention.self.value.bias', 'bert.encoder.layer.1.crossattention.output.dense.weight', 'bert.encoder.layer.1.crossattention.output.dense.bias', 'bert.encoder.layer.1.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.1.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.2.crossattention.self.query.weight', 'bert.encoder.layer.2.crossattention.self.query.bias', 'bert.encoder.layer.2.crossattention.self.key.weight', 'bert.encoder.layer.2.crossattention.self.key.bias', 'bert.encoder.layer.2.crossattention.self.value.weight', 'bert.encoder.layer.2.crossattention.self.value.bias', 'bert.encoder.layer.2.crossattention.output.dense.weight', 'bert.encoder.layer.2.crossattention.output.dense.bias', 'bert.encoder.layer.2.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.2.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.3.crossattention.self.query.weight', 'bert.encoder.layer.3.crossattention.self.query.bias', 'bert.encoder.layer.3.crossattention.self.key.weight', 'bert.encoder.layer.3.crossattention.self.key.bias', 'bert.encoder.layer.3.crossattention.self.value.weight', 'bert.encoder.layer.3.crossattention.self.value.bias', 'bert.encoder.layer.3.crossattention.output.dense.weight', 'bert.encoder.layer.3.crossattention.output.dense.bias', 'bert.encoder.layer.3.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.3.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.4.crossattention.self.query.weight', 'bert.encoder.layer.4.crossattention.self.query.bias', 'bert.encoder.layer.4.crossattention.self.key.weight', 'bert.encoder.layer.4.crossattention.self.key.bias', 'bert.encoder.layer.4.crossattention.self.value.weight', 'bert.encoder.layer.4.crossattention.self.value.bias', 'bert.encoder.layer.4.crossattention.output.dense.weight', 'bert.encoder.layer.4.crossattention.output.dense.bias', 'bert.encoder.layer.4.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.4.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.5.crossattention.self.query.weight', 'bert.encoder.layer.5.crossattention.self.query.bias', 'bert.encoder.layer.5.crossattention.self.key.weight', 'bert.encoder.layer.5.crossattention.self.key.bias', 'bert.encoder.layer.5.crossattention.self.value.weight', 'bert.encoder.layer.5.crossattention.self.value.bias', 'bert.encoder.layer.5.crossattention.output.dense.weight', 'bert.encoder.layer.5.crossattention.output.dense.bias', 'bert.encoder.layer.5.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.5.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.6.crossattention.self.query.weight', 'bert.encoder.layer.6.crossattention.self.query.bias', 'bert.encoder.layer.6.crossattention.self.key.weight', 'bert.encoder.layer.6.crossattention.self.key.bias', 'bert.encoder.layer.6.crossattention.self.value.weight', 'bert.encoder.layer.6.crossattention.self.value.bias', 'bert.encoder.layer.6.crossattention.output.dense.weight', 'bert.encoder.layer.6.crossattention.output.dense.bias', 'bert.encoder.layer.6.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.6.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.7.crossattention.self.query.weight', 'bert.encoder.layer.7.crossattention.self.query.bias', 'bert.encoder.layer.7.crossattention.self.key.weight', 'bert.encoder.layer.7.crossattention.self.key.bias', 'bert.encoder.layer.7.crossattention.self.value.weight', 'bert.encoder.layer.7.crossattention.self.value.bias', 'bert.encoder.layer.7.crossattention.output.dense.weight', 'bert.encoder.layer.7.crossattention.output.dense.bias', 'bert.encoder.layer.7.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.7.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.8.crossattention.self.query.weight', 'bert.encoder.layer.8.crossattention.self.query.bias', 'bert.encoder.layer.8.crossattention.self.key.weight', 'bert.encoder.layer.8.crossattention.self.key.bias', 'bert.encoder.layer.8.crossattention.self.value.weight', 'bert.encoder.layer.8.crossattention.self.value.bias', 'bert.encoder.layer.8.crossattention.output.dense.weight', 'bert.encoder.layer.8.crossattention.output.dense.bias', 'bert.encoder.layer.8.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.8.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.9.crossattention.self.query.weight', 'bert.encoder.layer.9.crossattention.self.query.bias', 'bert.encoder.layer.9.crossattention.self.key.weight', 'bert.encoder.layer.9.crossattention.self.key.bias', 'bert.encoder.layer.9.crossattention.self.value.weight', 'bert.encoder.layer.9.crossattention.self.value.bias', 'bert.encoder.layer.9.crossattention.output.dense.weight', 'bert.encoder.layer.9.crossattention.output.dense.bias', 'bert.encoder.layer.9.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.9.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.10.crossattention.self.query.weight', 'bert.encoder.layer.10.crossattention.self.query.bias', 'bert.encoder.layer.10.crossattention.self.key.weight', 'bert.encoder.layer.10.crossattention.self.key.bias', 'bert.encoder.layer.10.crossattention.self.value.weight', 'bert.encoder.layer.10.crossattention.self.value.bias', 'bert.encoder.layer.10.crossattention.output.dense.weight', 'bert.encoder.layer.10.crossattention.output.dense.bias', 'bert.encoder.layer.10.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.10.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.11.crossattention.self.query.weight', 'bert.encoder.layer.11.crossattention.self.query.bias', 'bert.encoder.layer.11.crossattention.self.key.weight', 'bert.encoder.layer.11.crossattention.self.key.bias', 'bert.encoder.layer.11.crossattention.self.value.weight', 'bert.encoder.layer.11.crossattention.self.value.bias', 'bert.encoder.layer.11.crossattention.output.dense.weight', 'bert.encoder.layer.11.crossattention.output.dense.bias', 'bert.encoder.layer.11.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.11.crossattention.output.LayerNorm.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
INFO:simpletransformers.seq2seq.seq2seq_utils: Creating features from dataset file at cache_dir/
100%|██████████| 2/2 [00:01<00:00,  1.41it/s]
INFO:simpletransformers.seq2seq.seq2seq_utils: Saving features into cached file cache_dir/cahya_bert-base-indonesian-522M-cahya_bert-base-indonesian-522M_cached_1282
INFO:simpletransformers.seq2seq.seq2seq_model: Training started
Epoch 1 of 5:   0%|          | 0/5 [00:00<?, ?it/s]
Running Epoch 0 of 5:   0%|          | 0/1 [00:00<?, ?it/s]
Epochs 0/5. Running Loss:   10.9282:   0%|          | 0/1 [00:01<?, ?it/s]
Epochs 0/5. Running Loss:   10.9282: 100%|██████████| 1/1 [00:07<00:00,  7.84s/it]
INFO:simpletransformers.seq2seq.seq2seq_model:Saving model into normalization/checkpoint-1-epoch-1
INFO:simpletransformers.seq2seq.seq2seq_utils: Creating features from dataset file at cache_dir/

100%|██████████| 2/2 [00:00<00:00, 722.04it/s]
INFO:simpletransformers.seq2seq.seq2seq_utils: Saving features into cached file cache_dir/cahya_bert-base-indonesian-522M-cahya_bert-base-indonesian-522M_cached_1282
INFO:simpletransformers.seq2seq.seq2seq_model:Saving model into normalization/checkpoint-1-epoch-1
Epoch 1 of 5:   0%|          | 0/5 [00:12<?, ?it/s]
Traceback (most recent call last):
  File "/Users/junaedifahmi/PycharmProject/hugging-your-face/textnormalization.py", line 53, in <module>
    model.train_model(
  File "/Users/junaedifahmi/PycharmProject/hugging-your-face/venv/lib/python3.8/site-packages/simpletransformers/seq2seq/seq2seq_model.py", line 310, in train_model
    global_step, training_details = self.train(
  File "/Users/junaedifahmi/PycharmProject/hugging-your-face/venv/lib/python3.8/site-packages/simpletransformers/seq2seq/seq2seq_model.py", line 737, in train
    report = pd.DataFrame(training_progress_scores)
  File "/Users/junaedifahmi/PycharmProject/hugging-your-face/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 529, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/Users/junaedifahmi/PycharmProject/hugging-your-face/venv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 287, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/Users/junaedifahmi/PycharmProject/hugging-your-face/venv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 80, in arrays_to_mgr
    index = extract_index(arrays)
  File "/Users/junaedifahmi/PycharmProject/hugging-your-face/venv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 401, in extract_index
    raise ValueError("arrays must all be same length")
ValueError: arrays must all be same length
```

the version that I used is `simpletransformers==0.60.9`

Also, I am not sure to overcome the _You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference._ problem. 

I really appreciate any inputs and answer. Thank you.

**Comment by ThilinaRajapakse** [comment]
Do you get the error after the first epoch is completed? Can you try running this without `evaluate_during_training`?

The error you are getting suggests something is off with the training dataset.

You can ignore the warning about training the model. That's expected when you load a pre-trained model.
