### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by DesiKeki** [ThilinaRajapakse/simpletransformers#108]
Hi,

I am trying the simple transformers classification model and I am getting following error while importing the ClassificationModel:

```
Traceback (most recent call last):
  File "bert_classification.py", line 2, in <module>
    from simpletransformers.classification import ClassificationModel
  File "C:\Users\vmitt\AppData\Local\Continuum\anaconda3\envs\transformers\lib\site-packages\simpletransformers\classification\__init__.py", line 1, in <module>
    from simpletransformers.classification.classification_model import ClassificationModel
  File "C:\Users\vmitt\AppData\Local\Continuum\anaconda3\envs\transformers\lib\site-packages\simpletransformers\classification\classification_model.py", line 18, in <module>
    from scipy.stats import pearsonr, mode
  File "C:\Users\vmitt\AppData\Local\Continuum\anaconda3\envs\transformers\lib\site-packages\scipy\__init__.py", line 106, in <module>
    from . import _distributor_init
  File "C:\Users\vmitt\AppData\Local\Continuum\anaconda3\envs\transformers\lib\site-packages\scipy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\vmitt\AppData\Local\Continuum\anaconda3\envs\transformers\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

I see that many dlls are present at the requested path, but I do not know which dll is missing. Please help me with this issue. Some of the details are as below:

```
Python version: 3.7.5
Cuda: cudatoolkit 10.1
Pytorch: pytorch-1.3.1
```

Kindly let me know what all information is needed to better understand the problem.

Thanks
Keki

**Comment by ThilinaRajapakse** [comment]
Looks like the error is being generated when importing scipy. Try installing it using conda.

`conda install scipy`

Windows is pretty bad for Pytorch and Deep Learning, so you might be better off switching to a linux environment for DL work.

**Comment by DesiKeki** [comment]
Thanks Thilina, that helped me unblock. After scipy I had to install following packages also:
```
scikit-learn (conda install -c anaconda scikit-learn)
regex (conda install -c conda-forge regex)
sentencepiece (conda install -c roccqqck sentencepiece)
```
After this, the training started, but soon I started getting following messages:

```
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 398.45 MiB already allocated; 0 bytes free; 33.55 MiB cached)
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 344.37 MiB already allocated; 10.35 MiB free; 27.63 MiB cached)

RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```
But seems like the training is still continuing... so I am letting it run. 
Can I move ahead with these errors in place?

Thanks
Keki

**Comment by ThilinaRajapakse** [comment]
It looks like you are running out of GPU memory. I'm not sure how the training is continuing as it should terminate when a RuntimeError is reached. I think it would be best to try reducing the train_batch_size until you don't get CUDA runtime errors.

**Comment by DesiKeki** [comment]
Thanks a lot @ThilinaRajapakse. Let me try that and if I still get any error, I'll get back with another thread. The error mentioned in the title of this thread is solved, so I will close this thread.

Thanks a lot again!
