### ISSUE TITLE
[NER fine-tuning] Unknown label error

### ISSUE THREAD

**Issue by AlexFridman** [ThilinaRajapakse/simpletransformers#1106]
Hello! I'm getting an exception "unknow label" when trying to fine-tune NER 
@ThilinaRajapakse 

**To Reproduce**
```python

import numpy as np
import pandas as pd
from scipy.special import softmax

from simpletransformers.ner import NERModel

data = [[0, 'I', 'O'],
 [0, 'really', 'O'],
 [0, 'enjoy', 'B-CON'],
 [0, 'the', 'I-CON'],
 [0, 'location', 'I-CON'],
 [0, 'and', 'O'],
 [0, 'the', 'O'],
 [0, 'staff', 'B-COM'],
 [0, 'here', 'I-COM'],
 [0, 'great', 'I-COM'],
 [0, 'people', 'I-COM'],
 [1, 'It', 'O'],
 [1, 'is', 'O'],
 [1, 'really', 'B-NOI'],
 [1, 'quiet', 'I-NOI'],
 [1, 'I', 'O'],
 [1, 'mean', 'O'],
 [1, 'there', 'O'],
 [1, 'will', 'O'],
 [1, 'be', 'O'],
 [1, 'people', 'B-NOI'],
 [1, 'playing', 'I-NOI'],
 [1, 'music', 'I-NOI'],
 [1, 'but', 'I-NOI'],
 [1, 'hey', 'I-NOI'],
 [1, 'everyone', 'I-NOI'],
 [1, 'loves', 'I-NOI'],
 [1, 'music', 'I-NOI'],
 [1, 'But', 'O'],
 [1, 'other', 'O']]

train_df = pd.DataFrame(data, columns=["sentence_id", "words", "labels"])

eval_df = pd.DataFrame(data, columns=["sentence_id", "words", "labels"])

# Create a NERModel
model = NERModel("bert", "bert-base-cased", args={"overwrite_output_dir": True, "reprocess_input_data": True})

model.train_model(train_df)
````

Traceback:
```
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/alex/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/alex/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/alex/.virtualenvs/jupyter/lib/python3.8/site-packages/simpletransformers/ner/ner_utils.py", line 185, in convert_examples_with_multiprocessing
    return [
  File "/home/alex/.virtualenvs/jupyter/lib/python3.8/site-packages/simpletransformers/ner/ner_utils.py", line 186, in <listcomp>
    convert_example_to_feature(
  File "/home/alex/.virtualenvs/jupyter/lib/python3.8/site-packages/simpletransformers/ner/ner_utils.py", line 252, in convert_example_to_feature
    label_ids.extend([label_map[label]] + [pad_token_label_id] * (len(word_tokens) - 1))
KeyError: 'B-CON'
"""

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-38-da265829e8d3> in <module>
     12 model = NERModel("bert", "bert-base-cased", args={"overwrite_output_dir": True, "reprocess_input_data": True})
     13 
---> 14 model.train_model(train_df)

~/.virtualenvs/jupyter/lib/python3.8/site-packages/simpletransformers/ner/ner_model.py in train_model(self, train_data, output_dir, show_running_loss, args, eval_data, verbose, **kwargs)
    338         self._move_model_to_device()
    339 
--> 340         train_dataset = self.load_and_cache_examples(train_data)
    341 
    342         os.makedirs(output_dir, exist_ok=True)
```

**Desktop (please complete the following information):**
 - OS: linux

**Comment by AlexFridman** [comment]
@ThilinaRajapakse please close the issue and add to the example setting of the "labels" parameter.
It's not obvious that this parameter exists and model does not extract complete list of labels out of dataset
