### ISSUE TITLE
How do I run the RAG model? Can you write a demo？please

### ISSUE THREAD

**Issue by ExplainRegex** [ThilinaRajapakse/simpletransformers#1121]
System: Win10
Description: When I try to load a local tsv file as "knowledge_dataset", it keeps reporting the error as follows:
`Downloading and preparing dataset csv/default (download: Unknown size, generated: Unknown size, post-processed: Unknown size, total: Unknown size) to C:\Users\yg\.cache\huggingface\datasets\csv\default-d26540e0fb86ebb6\0.0.0\2dc6629a9ff6b5697d82c25b73731dd440507a69cbce8b425db50b751e8fcfd0...
Traceback (most recent call last):
  File "D:\Anaconda\Lib\site-packages\datasets\builder.py", line 652, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "D:\Anaconda\Lib\site-packages\datasets\builder.py", line 1034, in _prepare_split
    for key, table in utils.tqdm(generator, unit=" tables", leave=False, disable=not_verbose):
  File "D:\Anaconda\Lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "D:\Anaconda\Lib\site-packages\datasets\packaged_modules\csv\csv.py", line 129, in _generate_tables
    chunksize=self.config.chunksize,
  File "D:\Anaconda\Lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "D:\Anaconda\Lib\site-packages\pandas\io\parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "D:\Anaconda\Lib\site-packages\pandas\io\parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "D:\Anaconda\Lib\site-packages\pandas\io\parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "D:\Anaconda\Lib\site-packages\pandas\io\parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 697, in pandas._libs.parsers.TextReader._setup_parser_source
OSError: Initializing from file failed

During handling of the above exception, another exception occurred:`
`Traceback (most recent call last):
  File "D:/毕设系列/RAG/demo.py", line 45, in <module>
    args=model_args,
  File "D:\毕设系列\RAG\simpletransformers\seq2seq\seq2seq_model.py", line 255, in __init__
    device=self.device,
  File "D:\毕设系列\RAG\simpletransformers\seq2seq\seq2seq_utils.py", line 380, in generate_faiss_index_dataset
    dataset = load_dataset("csv", data_files=data, delimiter="\t", column_names=["title", "text"])
  File "D:\Anaconda\Lib\site-packages\datasets\load.py", line 751, in load_dataset
    use_auth_token=use_auth_token,
  File "D:\Anaconda\Lib\site-packages\datasets\builder.py", line 575, in download_and_prepare
    dl_manager=dl_manager, verify_infos=verify_infos, **download_and_prepare_kwargs
  File "D:\Anaconda\Lib\site-packages\datasets\builder.py", line 658, in _download_and_prepare
    + str(e)
OSError: Cannot find data file. 
Original error:
Initializing from file failed`

Can you write a demo to load the tsv file from local and train the RAG model?please!

**Comment by NTDXYG** [comment]
I have the same confusion.
