### ISSUE TITLE
Streamlit simple viewer broken because of `@st.cache` issue

### ISSUE THREAD

**Issue by joachimdb** [ThilinaRajapakse/simpletransformers#1138]
**Describe the bug**
The Streamlit base simple viewer is broken

**To Reproduce**
Start the simple and load an XML-Roberta based multi-label classifier (tested, but I'm suspecting that the problem will occur with any type of model)

**Expected behavior**
Classifier model is loaded and then cached because of the `@st.cache` call here: https://github.com/ThilinaRajapakse/simpletransformers/blob/master/simpletransformers/streamlit/simple_view.py#L39

Instead, streamlit starts complaining:
```
While caching the body of `load_model()`, Streamlit encountered an
object of type `builtins.function`, which it does not know how to hash.

**In this specific case, it's very likely you found a Streamlit bug so please
[file a bug report here.]
(https://github.com/streamlit/streamlit/issues/new/choose)**

In the meantime, you can try bypassing this error by registering a custom
hash function via the `hash_funcs` keyword in @st.cache(). For example:


@st.cache(hash_funcs={builtins.function: my_hash_func})
def my_func(...):
    ...


If you don't know where the object of type `builtins.function` is coming
from, try looking at the hash chain below for an object that you do recognize,
then pass that to `hash_funcs` instead:


Object of type builtins.function: <function load_model at 0x7f9b5ada3790>


Please see the `hash_funcs` [documentation]
(https://docs.streamlit.io/en/stable/caching.html#the-hash-funcs-parameter)
for more details.

Traceback (most recent call last):
  File "/Users/joachim.debeule/opt/anaconda3/envs/st/lib/python3.9/site-packages/streamlit/hashing.py", line 352, in to_bytes
    b = b"%s:%s" % (tname, self._to_bytes(obj, context))
  File "/Users/joachim.debeule/opt/anaconda3/envs/st/lib/python3.9/site-packages/streamlit/hashing.py", line 608, in _to_bytes
    if self._file_should_be_hashed(obj.__code__.co_filename):
  File "/Users/joachim.debeule/opt/anaconda3/envs/st/lib/python3.9/site-packages/streamlit/hashing.py", line 387, in _file_should_be_hashed
    filepath, self._get_main_script_directory()
  File "/Users/joachim.debeule/opt/anaconda3/envs/st/lib/python3.9/site-packages/streamlit/hashing.py", line 692, in _get_main_script_directory
    main_path = __main__.__file__
AttributeError: module '__main__' has no attribute '__file__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/joachim.debeule/opt/anaconda3/envs/st/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/joachim.debeule/opt/anaconda3/envs/st/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/joachim.debeule/opt/anaconda3/envs/st/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/joachim.debeule/opt/anaconda3/envs/st/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/joachim.debeule/opt/anaconda3/envs/st/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/joachim.debeule/opt/anaconda3/envs/st/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/joachim.debeule/opt/anaconda3/envs/st/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/joachim.debeule/workspace/nlp-spikes/cross-lingual/simple-transformers/simple_view.py", line 188, in <module>
    streamlit_runner()
  File "/Users/joachim.debeule/workspace/nlp-spikes/cross-lingual/simple-transformers/simple_view.py", line 171, in streamlit_runner
    model, model_class = load_model(
  File "/Users/joachim.debeule/opt/anaconda3/envs/st/lib/python3.9/site-packages/streamlit/caching.py", line 573, in wrapped_func
    return get_or_create_cached_value()
  File "/Users/joachim.debeule/opt/anaconda3/envs/st/lib/python3.9/site-packages/streamlit/caching.py", line 498, in get_or_create_cached_value
    cache_key = _hash_func(func, hash_funcs)
  File "/Users/joachim.debeule/opt/anaconda3/envs/st/lib/python3.9/site-packages/streamlit/caching.py", line 624, in _hash_func
    update_hash(
  File "/Users/joachim.debeule/opt/anaconda3/envs/st/lib/python3.9/site-packages/streamlit/hashing.py", line 92, in update_hash
    ch.update(hasher, val, context)
  File "/Users/joachim.debeule/opt/anaconda3/envs/st/lib/python3.9/site-packages/streamlit/hashing.py", line 377, in update
    b = self.to_bytes(obj, context)
  File "/Users/joachim.debeule/opt/anaconda3/envs/st/lib/python3.9/site-packages/streamlit/hashing.py", line 366, in to_bytes
    raise InternalHashError(e, obj)
  File "/Users/joachim.debeule/opt/anaconda3/envs/st/lib/python3.9/site-packages/streamlit/hashing.py", line 352, in to_bytes
    b = b"%s:%s" % (tname, self._to_bytes(obj, context))
  File "/Users/joachim.debeule/opt/anaconda3/envs/st/lib/python3.9/site-packages/streamlit/hashing.py", line 608, in _to_bytes
    if self._file_should_be_hashed(obj.__code__.co_filename):
  File "/Users/joachim.debeule/opt/anaconda3/envs/st/lib/python3.9/site-packages/streamlit/hashing.py", line 387, in _file_should_be_hashed
    filepath, self._get_main_script_directory()
  File "/Users/joachim.debeule/opt/anaconda3/envs/st/lib/python3.9/site-packages/streamlit/hashing.py", line 692, in _get_main_script_directory
    main_path = __main__.__file__
```

**Comment by joachimdb** [comment]
i've filed an issue for this to Streamlit too: https://github.com/streamlit/streamlit/issues/3290
