### ISSUE TITLE
error on seq2seq on multi-gpu

### ISSUE THREAD

**Issue by tiru1930** [ThilinaRajapakse/simpletransformers#1141]
```

RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    "them on device: {}".format(self.src_device_obj, t.device))
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cuda:1
````

code 

```
model_args = {
    "reprocess_input_data": True,
    "overwrite_output_dir": True,
    "max_seq_length": 100,
    "train_batch_size":20,
    "num_train_epochs": 100,
    "save_eval_checkpoints": False,
    "save_model_every_epoch": False,
    # "silent": True,
    "evaluate_generated_text": True,
    "evaluate_during_training": True,
    "evaluate_during_training_verbose": True,
    "use_multiprocessing": False,
    "use_multiprocessing_for_evaluation": False,
    "save_best_model": True,
    "max_length": 100,
    "fp16":True,
    "n_gpu":2
}

model = Seq2SeqModel("bert", "bert-base-cased", "bert-base-cased", args=model_args,use_cuda=True)


def count_matches(labels, preds):
    print("labels lenght ",len(labels))
    print("sample lables ",labels[:4])
    print("preds lenght ",len(preds))
    print("sample preds", preds[:4])
    return sum([1 if label == pred else 0 for label, pred in zip(labels, preds)])


model.train_model(df_train.sample(10000), eval_data=df_test.sample(10000), matches=count_matches)
```

**Comment by Soulscb** [comment]
did you solve the problem?

**Comment by tiru1930** [comment]
no, i can see the problem still , so ran it on single gpu
