### ISSUE TITLE
CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by SirAlexI** [ThilinaRajapakse/simpletransformers#1196]
When moving from 1 gpu to 2 gpu, I get the following error:

  File "/home/server/Escritorio/AlejandroF/agfa/simple-transformers/train_language_model.py", line 138, in <module>
    model.train_model(train_filename)
  File "/home/server/anaconda3/envs/agfa/lib/python3.9/site-packages/simpletransformers/language_modeling/language_modeling_model.py", line 431, in train_model
    global_step, training_details = self.train(
  File "/home/server/anaconda3/envs/agfa/lib/python3.9/site-packages/simpletransformers/language_modeling/language_modeling_model.py", line 774, in train
    model(inputs, labels=labels)
  File "/home/server/anaconda3/envs/agfa/lib/python3.9/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/server/anaconda3/envs/agfa/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/server/anaconda3/envs/agfa/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/server/anaconda3/envs/agfa/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/server/anaconda3/envs/agfa/lib/python3.9/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/server/anaconda3/envs/agfa/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/server/anaconda3/envs/agfa/lib/python3.9/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/server/anaconda3/envs/agfa/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 1329, in forward
    outputs = self.bert(
  File "/home/server/anaconda3/envs/agfa/lib/python3.9/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/server/anaconda3/envs/agfa/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 991, in forward
    encoder_outputs = self.encoder(
  File "/home/server/anaconda3/envs/agfa/lib/python3.9/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/server/anaconda3/envs/agfa/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 582, in forward
    layer_outputs = layer_module(
  File "/home/server/anaconda3/envs/agfa/lib/python3.9/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/server/anaconda3/envs/agfa/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 470, in forward
    self_attention_outputs = self.attention(
  File "/home/server/anaconda3/envs/agfa/lib/python3.9/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/server/anaconda3/envs/agfa/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 401, in forward
    self_outputs = self.self(
  File "/home/server/anaconda3/envs/agfa/lib/python3.9/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/server/anaconda3/envs/agfa/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 267, in forward
    mixed_query_layer = self.query(hidden_states)
  File "/home/server/anaconda3/envs/agfa/lib/python3.9/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/server/anaconda3/envs/agfa/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/server/anaconda3/envs/agfa/lib/python3.9/site-packages/torch/nn/functional.py", line 1692, in linear
    output = input.matmul(weight.t())
**RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`**

Training bert with the following parameters:

{'train_batch_size': 8, 'reprocess_input_data': True, 'overwrite_output_dir': True, 'output_dir': '/home/server/Escritorio/AlejandroF/agfa/simple-transformers/models-bert-t-r/', 'best_model_dir': '/home/server/Escritorio/AlejandroF/agfa/simple-transformers/models-bert-t-r/best_model/', 'max_seq_length': 128, 'num_train_epochs': 1, 'n_gpu': 2, 'fp16': True, 'gradient_accumulation_steps': 1, 'process_count': 48, 'use_multiprocessing': True, 'save_model_every_epoch': True, 'save_best_model': True, 'save_eval_checkpoints': False, 'save_steps': 5000, 'sliding_window': True, 'stride': 0.9, 'dataset_type': 'simple', 'vocab_size': 169488, 'no_save': False, 'min_frequency': 1}

Linux server-ProLiant-ML350-Gen10 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Running on miniconda:

_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
altair                    4.1.0                    pypi_0    pypi
argon2-cffi               20.1.0                   pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
async-generator           1.10                     pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
base58                    2.1.0                    pypi_0    pypi
blas                      1.0                         mkl  
bleach                    3.3.0                    pypi_0    pypi
blinker                   1.4                      pypi_0    pypi
bottleneck                1.3.2            py39hdd57654_1  
ca-certificates           2021.7.5             h06a4308_1  
cachetools                4.2.2                    pypi_0    pypi
certifi                   2021.5.30        py39h06a4308_0  
cffi                      1.14.6                   pypi_0    pypi
chardet                   4.0.0                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
configparser              5.0.2                    pypi_0    pypi
cudatoolkit               10.2.89              h8f6ccaa_8    conda-forge
datasets                  1.9.0                    pypi_0    pypi
debugpy                   1.3.0                    pypi_0    pypi
decorator                 5.0.9                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
dill                      0.3.4                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
filelock                  3.0.12                   pypi_0    pypi
freetype                  2.10.4               h0708190_1    conda-forge
fsspec                    2021.6.1                 pypi_0    pypi
gitdb                     4.0.7                    pypi_0    pypi
gitpython                 3.1.18                   pypi_0    pypi
huggingface-hub           0.0.12                   pypi_0    pypi
idna                      2.10                     pypi_0    pypi
importlib-metadata        3.10.0           py39h06a4308_0  
ipykernel                 6.0.1                    pypi_0    pypi
ipython                   7.25.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.6.3                    pypi_0    pypi
jedi                      0.18.0                   pypi_0    pypi
jinja2                    3.0.1                    pypi_0    pypi
joblib                    1.0.1              pyhd3eb1b0_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                3.2.0                    pypi_0    pypi
jupyter-client            6.1.12                   pypi_0    pypi
jupyter-core              4.7.1                    pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jupyterlab-widgets        1.0.0                    pypi_0    pypi
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.36.1               hea4e1c9_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
libtiff                   4.2.0                h85742a9_0  
libwebp-base              1.2.0                h7f98852_2    conda-forge
llvm-openmp               11.1.0               h4bd325d_1    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
markupsafe                2.0.1                    pypi_0    pypi
matplotlib-inline         0.1.2                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mkl                       2021.3.0           h726a3e6_557    conda-forge
mkl-service               2.4.0            py39h3811e60_0    conda-forge
mkl_fft                   1.3.0            py39h42c9631_2  
mkl_random                1.2.2            py39hde0f152_0    conda-forge
multiprocess              0.70.12.2                pypi_0    pypi
nbclient                  0.5.3                    pypi_0    pypi
nbconvert                 6.1.0                    pypi_0    pypi
nbformat                  5.1.3                    pypi_0    pypi
ncurses                   6.2                  h58526e2_4    conda-forge
nest-asyncio              1.5.1                    pypi_0    pypi
ninja                     1.10.2               h4bd325d_0    conda-forge
nltk                      3.6.2              pyhd3eb1b0_0  
notebook                  6.4.0                    pypi_0    pypi
numexpr                   2.7.3            py39h22e1b3c_1  
numpy                     1.20.2           py39h2d18471_0  
numpy-base                1.20.2           py39hfae3a4d_0  
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1k               h27cfd23_0  
packaging                 21.0                     pypi_0    pypi
pandas                    1.2.5            py39h295c915_0  
pandocfilters             1.4.3                    pypi_0    pypi
parso                     0.8.2                    pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.3.1            py39h2c7a002_0  
pip                       21.1.3             pyhd8ed1ab_0    conda-forge
prometheus-client         0.11.0                   pypi_0    pypi
promise                   2.3                      pypi_0    pypi
prompt-toolkit            3.0.19                   pypi_0    pypi
protobuf                  3.17.3                   pypi_0    pypi
psutil                    5.8.0                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pyarrow                   4.0.1                    pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pydeck                    0.6.2                    pypi_0    pypi
pygments                  2.9.0                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyrsistent                0.18.0                   pypi_0    pypi
python                    3.9.6           h49503c6_1_cpython    conda-forge
python-dateutil           2.8.1              pyhd3eb1b0_0  
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.7.1           py3.9_cuda10.2.89_cudnn7.6.5_0    pytorch
pytz                      2021.1             pyhd3eb1b0_0  
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.1.0                   pypi_0    pypi
readline                  8.1                  h46c0cb4_0    conda-forge
regex                     2021.7.6         py39h7f8727e_0  
requests                  2.25.1                   pypi_0    pypi
sacremoses                0.0.45                   pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.7.0                    pypi_0    pypi
send2trash                1.7.1                    pypi_0    pypi
sentencepiece             0.1.96                   pypi_0    pypi
sentry-sdk                1.3.0                    pypi_0    pypi
seqeval                   1.2.2                    pypi_0    pypi
setuptools                49.6.0           py39hf3d152e_3    conda-forge
shortuuid                 1.0.1                    pypi_0    pypi
simpletransformers        0.61.9                   pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     4.0.0                    pypi_0    pypi
sqlite                    3.36.0               h9cd32fc_0    conda-forge
streamlit                 0.84.1                   pypi_0    pypi
subprocess32              3.5.4                    pypi_0    pypi
tbb                       2021.3.0             h4bd325d_0    conda-forge
tensorboardx              2.4                      pypi_0    pypi
terminado                 0.10.1                   pypi_0    pypi
testpath                  0.5.0                    pypi_0    pypi
threadpoolctl             2.2.0                    pypi_0    pypi
tk                        8.6.10               h21135ba_1    conda-forge
tokenizers                0.10.3                   pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
toolz                     0.11.1                   pypi_0    pypi
torchaudio                0.7.2                      py39    pytorch
torchvision               0.8.2                py39_cu102    pytorch
tornado                   6.1                      pypi_0    pypi
tqdm                      4.61.2             pyhd3eb1b0_1  
traitlets                 5.0.5                    pypi_0    pypi
transformers              4.8.2                    pypi_0    pypi
typing_extensions         3.10.0.0           pyha770c72_0    conda-forge
tzdata                    2021a                he74cb21_1    conda-forge
tzlocal                   2.1                      pypi_0    pypi
urllib3                   1.26.6                   pypi_0    pypi
validators                0.18.2                   pypi_0    pypi
wandb                     0.10.33                  pypi_0    pypi
watchdog                  2.1.3                    pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
widgetsnbextension        3.5.1                    pypi_0    pypi
xxhash                    2.0.2                    pypi_0    pypi
xz                        5.2.5                h516909a_1    conda-forge
zipp                      3.5.0              pyhd3eb1b0_0  
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge

**Comment by SirAlexI** [comment]
I got this answer, but I do not how to implement it.
I guess a new version of simple transformers must be out soon.

https://discuss.pytorch.org/t/cuda-error-cublas-status-not-initialized-when-calling-cublascreate-handle/125450/4

nn.DataParallel (which seems to be used in your use case) could create an imbalanced memory usage and could thus cause an OOM on the default device, which is why we recommend to use DistributedDataParallel with a single process per GPU instead.
I assume you are also running OOM, so I would recommend to try to apply DDP.
