### ISSUE TITLE
Multilabel evaluation metrics: How to use Accuracy, F1-Score, Confusion Metrics

### ISSUE THREAD

**Issue by hieudango** [ThilinaRajapakse/simpletransformers#125]
**Describe the bug**
Hi @ThilinaRajapakse , I was still following your multilabel example and toxic comment multilabel example. When I tried other evaluation metrics (Accuracy, F1-Score, Confusion Metrics):

result, model_outputs, wrong_predictions = model.eval_model(eval_df, output_dir=MODEL_DIRECTORY, roc_auc=sklearn.metrics.roc_auc_score, accuracy=sklearn.metrics.accuracy_score)

Got this error:
File "/home/ec2-user/anaconda3/envs/st_env/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 90, in _check_targets
    "and {1} targets".format(type_true, type_pred))
**ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets**

The same thing happens with sklearn.metrics.multilabel_confusion_matrix and sklearn.metrics.f1_score. The only thing that works is sklearn.metrics.roc_auc_score.

More detailed logs:

Traceback (most recent call last):
  File "email_model_init_evaluate.py", line 55, in <module>
    result, model_outputs, wrong_predictions = model.eval_model(eval_df, output_dir=MODEL_DIRECTORY, roc_auc=sklearn.metrics.roc_auc_score, accuracy=sklearn.metrics.accuracy_score)
  File "/home/ec2-user/anaconda3/envs/st_env/lib/python3.7/site-packages/simpletransformers/classification/multi_label_classification_model.py", line 123, in eval_model
    return super().eval_model(eval_df, output_dir=output_dir, multi_label=multi_label, verbose=verbose, **kwargs)
  File "/home/ec2-user/anaconda3/envs/st_env/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 382, in eval_model
    result, model_outputs, wrong_preds = self.evaluate(eval_df, output_dir, multi_label=multi_label, **kwargs)
  File "/home/ec2-user/anaconda3/envs/st_env/lib/python3.7/site-packages/simpletransformers/classification/multi_label_classification_model.py", line 126, in evaluate
    return super().evaluate(eval_df, output_dir, multi_label=multi_label, prefix=prefix, **kwargs)
  File "/home/ec2-user/anaconda3/envs/st_env/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 481, in evaluate
    result, wrong = self.compute_metrics(preds, out_label_ids, eval_examples, **kwargs)
  File "/home/ec2-user/anaconda3/envs/st_env/lib/python3.7/site-packages/simpletransformers/classification/multi_label_classification_model.py", line 132, in compute_metrics
    return super().compute_metrics(preds, labels, eval_examples, multi_label=multi_label, **kwargs)
  File "/home/ec2-user/anaconda3/envs/st_env/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 585, in compute_metrics
    extra_metrics[metric] = func(labels, preds)
  File "/home/ec2-user/anaconda3/envs/st_env/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 185, inaccuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/home/ec2-user/anaconda3/envs/st_env/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 90, in _check_targets
    "and {1} targets".format(type_true, type_pred))
**ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets**

Also what is the meaning of multi_label=False and why don't you set multi_label=True when you call train_model and eval_model for multilabel examples?
def train_model(self, train_df, **multi_label=False**, output_dir=None, show_running_loss=True, args=None, eval_df=None, **kwargs)

def eval_model(self, eval_df, **multi_label=False**, output_dir=None, verbose=False, **kwargs)

**SUMMARY:**
1. Which metrics are available for multilabel classification, and how to use F1-Score, Accuracy for each class, confusion metrics for multilabel classification? Because currently all those mentioned metrics are not compatible with multilabel examples.
2. Why don't you set multi_label=True when you call train_model and eval_model for multilabel classification?

Thanks a lot!

**Comment by ThilinaRajapakse** [comment]
It's hard to support arbitrary metrics for multilabel classification. Because of that, I didn't even add this in the beginning but I think it must have slipped in through a PR.

The main issue here is that the predictions are not automatically rounded off to 0 or 1 with multilabel as it is done with single label tasks. The reason is that the correct way to round off is highly dependent on the situation at hand. The sklearn metric functions don't support continuous outputs with multilabel tasks, hence the error.

To get it to work, you'll have to handle the rounding off yourself. For example, you could write a wrapper function around the `f1_score()` function to handle the rounding off and pass in that function as a kwarg to `eval_model()`. The wrapper function should expect two arguments (y_true, y_pred) and return the score.

`multi_label` is set to `True` in `multilabel_classification_model.py`

**Comment by phrenol** [comment]
@hieudango where you able to create a working solution?

**Comment by hieudango** [comment]
@ThilinaRajapakse @phrenol 
Yes I created custom evaluation metric function based on sklearn metrics and set accuracy threshold (for example 0.5) Then I round up all values of predicted based on the threshold, and then use the sklearn metrics (Multilabel confusion metrics, accuracy, etc.)

I also learned to implement transformers from scratch to maximize customization :D

I'll leave this issue as open for couple more days to see if anyone has the same issue. Otherwise I'll close the issue.

**Comment by jasmeet12** [comment]
@hieudango I am facing a similar issue, however, when I threshold the predictions and try to use accuracy score, I am still getting the same error. My main concern is what are you sending as true_labels? I am using  sklearn MultiLabelBinarizer to encode the classes.

**Comment by vtrokhymenko** [comment]
so, when u @ThilinaRajapakse fixed problem with f1-score at `MultiLabelClassificationModel`?
because it's very important for multilabel!

**Comment by ThilinaRajapakse** [comment]
There is no problem to fix. That's just how multilabel classification works with sklearn. The metric functions you give need to take in the labels and the predictions and output some kind of a score. I can't control anything between calling the function and getting the output.

**Comment by MrRace** [comment]
For multilabel classification I set 
```
from sklearn.metrics import f1_score
result, model_outputs, wrong_predictions = model.eval_model(eval_df, f1=f1_score)
```
But for multilabel classification, I should pass a function like `f1_score(test_array, prediction_array, average='macro')`, how can I pass the core parameter ‘ average='macro'’ in `result, model_outputs, wrong_predictions = model.eval_model(eval_df, f1=f1_score)`?  Thanks a lot!

**Comment by ThilinaRajapakse** [comment]
You could write a wrapper function or use a lambda function.

**Comment by Sphinxs** [comment]
Even with a wrapper, `f1_score` considers the 'one-hot encode' (labels as 0s and 1s) as invalid output:

> You appear to be using a legacy multi-label data representation. Sequence of sequences are no longer supported; use a binary array or sparse matrix instead - the MultiLabelBinarizer transformer can convert to this format.

You need to trasnform it:

```python
# Section
train_data, evaluation_data = train_test_split(
    model_data,
    test_size=.15,
    stratify=model_data['Labels'],
    random_state=0
)

# Section
from sklearn.metrics import f1_score

from sklearn.preprocessing import MultiLabelBinarizer

def f1(predictions, outputs):
    mlb = MultiLabelBinarizer()
    
    return f1_score(
        mlb.fit_transform(evaluation_data['Labels']),
        mlb.fit_transform(predictions),
        average='weighted'
    )

result, model_outputs, wrong_predictions = model.eval_model(evaluation_data, f1=f1)

result
```

I'm using weighted for multi-label, see the other [options](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_score.html).

**Comment by Adel-Memariani** [comment]
> @ThilinaRajapakse

It would be really nice and helpful if you can share your code regarding your custom evaluation metric function based on sklearn metrics.

**Comment by Adel-Memariani** [comment]
@hieucnguyen, can you please share your code?

I tried to implement my own wrapper, it works, but the problem is the prediction probabilities (the second parameters that my wrapper gets) are quickly becoming close to 0 and so my metrics are useless (returning 0.0). I wonder how the LRAP is working in line 1267 of the classification_model.py?

```
if multi_label:
            label_ranking_score = label_ranking_average_precision_score(labels, preds)
            return {**{"LRAP": label_ranking_score}, **extra_metrics}, wrong 
```

**Comment by Sphinxs** [comment]
Just to make a note about the F1 and the problem that Adel has, in the case of F1 I think that if you convert the values through `MultiLabelBinarizer`  you're gonna have a useless metric at the end, once all the values used to calculate the F1 (accuracy and recall) are gonna be 1 and the same would happen to the original values that are also binary, I can be wrong but it would be necessary to have a map and a reverse map to make the use of theses metrics in a correct way, right?!?

F1 Notation:

![image](https://pmirla.github.io/assets/harmonic_mean.gif)

**Comment by Adel-Memariani** [comment]
> Just a note about the F1 and the problem that Adel has, in the case of F1 I think that if you convert the values through `MultiLabelBinarizer` you're gonna have a useless metric at the end, once all the values used to calculate the F1 (accuracy and recall) are gonna be 1 or 0 and the same for the original values that are also binary. I can be wrong but it would be necessary to have a map and a reverse map inside the model (kinda related to [this](https://github.com/ThilinaRajapakse/simpletransformers/issues)) to make use of metrics in a correct way, right?!?
> 
> F1 Notation:
> 
> ![image](https://camo.githubusercontent.com/58f711185a6bf30b582c775310f2e0f1feced9d35b569eb361304b456b0e276c/68747470733a2f2f706d69726c612e6769746875622e696f2f6173736574732f6861726d6f6e69635f6d65616e2e676966)

@Sphinxs, Thank you so much for your answer. I managed to fix the issue by normalizing my probabilities. I observed that the low values for the probabilities that I mentioned before has a valid reason and the probabilities after the first few steps are far smaller. However they are more meaningful (due to reduced error [updated weights] that resulted in a lower loss). Therefore we MUST normalize the probabilities before applying the threshold.

As a conclusion, I suggest to close this issue because the problem is not related to the Simpletransformers library and as @ThilinaRajapakse mentioned it depends on the use case. As a result a user can implement a custom wrapper for the problem. 

@ThilinaRajapakse Thank you for this great library.

**Comment by Adel-Memariani** [comment]
@Sphinxs, Thank you for your answer. I managed to fix the issue by normalizing my probabilities. I observed that the low values for the probabilities that I mentioned before has a valid reason and the probabilities after the first few steps are far smaller. Therefore we must normalize the probabilities before applying the threshold.
