### ISSUE TITLE
RuntimeError: received 0 items of ancdata

### ISSUE THREAD

**Issue by tramya28** [ThilinaRajapakse/simpletransformers#1292]
**Describe the bug**
I recently updated my pytorch and simple transformers versions. 
Previously I used these versions
SimpleTransformers=0.45.4
Torch=1.6.0
I updated the libraries to be able to use bertweet and ever since I updated, I am running into this error and could not run my previous successful models like bert and roberta

SimpleTransformers ==0.62.2
Torch==1.8.0
Exception in thread Thread-3:
Traceback (most recent call last):
File "/data/student_work/ramya_work/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
self.run()
File "/data/student_work/ramya_work/anaconda3/lib/python3.7/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/data/student_work/ramya_work/anaconda3/lib/python3.7/multiprocessing/pool.py", line 470, in _handle_results
task = get()
File "/data/student_work/ramya_work/anaconda3/lib/python3.7/multiprocessing/connection.py", line 251, in recv
return _ForkingPickler.loads(buf.getbuffer())
File "/data/ramya_work/Transformers/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 282, in rebuild_storage_fd
fd = df.detach()
File "/data/ramya_work/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 58, in detach
return reduction.recv_handle(conn)
File "/data/ramya_work/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 185, in recv_handle
return recvfds(s, 1)[0]
File "/data/ramya_work/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 161, in recvfds
len(ancdata))
RuntimeError: received 0 items of ancdata

I tried to roll back to the previous versions and still I keep getting the same error. 
**To Reproduce**

if model_name == "bert":
    model = ClassificationModel('bert', 'bert-large-uncased', args=model_args, num_labels=2) 

model.train_model(train_df, eval_df = eval_df)

**Comment by prigioni** [comment]
> 

It works, tkank you.

**Comment by prigioni** [comment]
> Try this:
> 
> ```
> import torch
> torch.multiprocessing.set_sharing_strategy('file_system')
> ```

It works, thank you.
