### ISSUE TITLE
How to Load Pre-trained Models without Network?

### ISSUE THREAD

**Issue by zzy-ucas** [ThilinaRajapakse/simpletransformers#1311]
Thanks for this project! It is very helpful! But I have a problem now.
I want to use this project in non-network servers. So, the probelm is, when I try to run `examples/seq2seq/paraphrasing/train.py`, it occurs:

```D:\Anaconda3\envs\st\python.exe "D:\Program Files (x86)\PyCharm\plugins\python\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 3596 --file D:/Github_Source_Code/1_ImageCaption/simpletransformers/examples/seq2seq/paraphrasing/train.py
pydev debugger: process 10512 is connecting

Connected to pydev debugger (build 193.7288.30)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\st\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "D:\Anaconda3\envs\st\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "D:\Anaconda3\envs\st\lib\socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\st\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "D:\Anaconda3\envs\st\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "D:\Anaconda3\envs\st\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "D:\Anaconda3\envs\st\lib\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "D:\Anaconda3\envs\st\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001767963E100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\st\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\Anaconda3\envs\st\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "D:\Anaconda3\envs\st\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/facebook/bart-base (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001767963E100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\st\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda3\envs\st\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda3\envs\st\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda3\envs\st\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/facebook/bart-base (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001767963E100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```

I have download `fackbook/bart-base` pre-trained model files and comment the `wandb_project`
```
# model_args.wandb_project = "Paraphrasing with BART"
```
I just want to load the pre-trained models, and finetune it on my dataset, and use it as an inference mode.
What can I do to solve this problem? Hope to solve this problem! Thanks a lot!

**Comment by ThilinaRajapakse** [comment]
You can provide the local path to the downloaded pretrained model as the `model_name` instead of something like `facebook/bart-base`.
