### ISSUE TITLE
Error in training an NER Model with custom labels

### ISSUE THREAD

**Issue by riteshkrjnu** [ThilinaRajapakse/simpletransformers#1351]
I am trying to use the library to train a part-of-speech model using the NERModel class - this obviously means I am using custom set of labels. Here is what I am doing -

```
all_labels = ['PART', 'CCONJ', 'ADJ', 'ADP', 'SCONJ', 'SYM', 'AUX', 'INTJ', 'PROPN', 'ADV', 'PUNCT', 'DET', 'PRON', 'Suffix', 'no', 'VERB', 'NOUN', 'NUM', 'X']

model_args = NERArgs()
model_args.labels_list = all_labels
model_args.train_batch_size = 16 #try 12, 6 in case of out of memory
model_args.max_seq_length = 512
model_args.evaluate_during_training = True
model_args.learning_rate = 6e-5
model_args.num_train_epochs = 10
model_args.save_model_every_epoch = True
model_args.evaluate_during_training_verbose = True
model_args.logging_steps = 50
model_args.output_dir = OUTPUT_DIR
model_args.best_model_dir = BEST_MODEL_DIR

model = NERModel('bert', 'google/muril-base-cased', labels=all_labels, args=model_args, use_cuda=cuda_available)
model.train_model(train_data, eval_data = eval_data, output_dir=OUTPUT_DIR, acc=sklearn.metrics.accuracy_score)

```

This results in the following error -
```
INFO:simpletransformers.ner.ner_model: Converting to features started.
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.7/dist-packages/simpletransformers/ner/ner_utils.py", line 233, in convert_examples_with_multiprocessing
    for example in example_group
  File "/usr/local/lib/python3.7/dist-packages/simpletransformers/ner/ner_utils.py", line 233, in <listcomp>
    for example in example_group
  File "/usr/local/lib/python3.7/dist-packages/simpletransformers/ner/ner_utils.py", line 292, in convert_example_to_feature
    print ('Label', label)
KeyError: 'O'
"""
The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)

/tmp/ipykernel_337/3518032987.py in <module>
      1 # Train the model
      2 model.train_model(train_data, eval_data = eval_data, output_dir=OUTPUT_DIR, 
----> 3                   acc=sklearn.metrics.accuracy_score)

/usr/local/lib/python3.7/dist-packages/simpletransformers/ner/ner_model.py in train_model(self, train_data, output_dir, show_running_loss, args, eval_data, verbose, **kwargs)
    452         self._move_model_to_device()
    453 
--> 454         train_dataset = self.load_and_cache_examples(train_data)
    455 
    456         os.makedirs(output_dir, exist_ok=True)

/usr/local/lib/python3.7/dist-packages/simpletransformers/ner/ner_model.py in load_and_cache_examples(self, data, evaluate, no_cache, to_predict)
   1811                         chunksize=args.multiprocessing_chunksize,
   1812                         mode=mode,
-> 1813                         use_multiprocessing_for_evaluation=args.use_multiprocessing_for_evaluation,
   1814                     )
   1815 

/usr/local/lib/python3.7/dist-packages/simpletransformers/ner/ner_utils.py in convert_examples_to_features(examples, label_list, max_seq_length, tokenizer, cls_token_at_end, cls_token, cls_token_segment_id, sep_token, sep_token_extra, pad_on_left, pad_token, pad_token_segment_id, pad_token_label_id, sequence_a_segment_id, mask_padding_with_zero, process_count, chunksize, silent, use_multiprocessing, mode, use_multiprocessing_for_evaluation)
    476                         examples,
    477                         chunksize=chunksize,
--> 478                     ),
    479                     total=len(examples),
    480                     disable=silent,

/usr/local/lib/python3.7/dist-packages/tqdm/notebook.py in __iter__(self)
    255     def __iter__(self):
    256         try:
--> 257             for obj in super(tqdm_notebook, self).__iter__():
    258                 # return super(tqdm...) will not catch exception
    259                 yield obj

/usr/local/lib/python3.7/dist-packages/tqdm/std.py in __iter__(self)
   1178 
   1179         try:
-> 1180             for obj in iterable:
   1181                 yield obj
   1182                 # Update and possibly print the progressbar.

/usr/lib/python3.7/multiprocessing/pool.py in <genexpr>(.0)
    323                     result._set_length
    324                 ))
--> 325             return (item for chunk in result for item in chunk)
    326 
    327     def imap_unordered(self, func, iterable, chunksize=1):

/usr/lib/python3.7/multiprocessing/pool.py in next(self, timeout)
    746         if success:
    747             return value
--> 748         raise value
    749 
    750     __next__ = next                    # XXX

/usr/lib/python3.7/multiprocessing/pool.py in worker()
    119         job, i, func, args, kwds = task
    120         try:
--> 121             result = (True, func(*args, **kwds))
    122         except Exception as e:
    123             if wrap_exception and func is not _helper_reraises_exception:

/usr/lib/python3.7/multiprocessing/pool.py in mapstar()
     42 
     43 def mapstar(args):
---> 44     return list(map(*args))
     45 
     46 def starmapstar(args):

/usr/local/lib/python3.7/dist-packages/simpletransformers/ner/ner_utils.py in convert_examples_with_multiprocessing()
    231             mask_padding_with_zero,
    232         )
--> 233         for example in example_group
    234     ]
    235 

/usr/local/lib/python3.7/dist-packages/simpletransformers/ner/ner_utils.py in <listcomp>()
    231             mask_padding_with_zero,
    232         )
--> 233         for example in example_group
    234     ]
    235 

/usr/local/lib/python3.7/dist-packages/simpletransformers/ner/ner_utils.py in convert_example_to_feature()
    290                 tokens.extend(word_tokens)
    291                 print ('Label map', label_map)
--> 292                 print ('Label', label)
    293             label_ids.extend(
    294                 [label_map[label]] + [pad_token_label_id] * (len(word_tokens) - 1)

KeyError: 'O'

```

There are no labels called 'O' in either the train or eval file. And both are provided as input in CONLL format. Is there something wrong that I am doing or an issue in the code?

I am using the following versions -
`tokenizers-0.10.3 transformers-4.15.0 simpletransformers-0.63.4`

**Comment by DebanjanaKar** [comment]
@riteshkrjnu how did you resolve it?
