### ISSUE TITLE
Multiple GPU issue

### ISSUE THREAD

**Issue by elleobrien** [ThilinaRajapakse/simpletransformers#197]
Hello, this is a wonderful library and has been very easy for me to use so far! The only issue I'm having is going from 1 -> multiple GPUs. I am doing binary classification (Torch version = 1.2.0; also tried Torch 1.4.0)

When I set n_gpu = 4, as is the case on my EC2 machine, I get this error:

```Traceback (most recent call last):                                               | 0/30976 [00:00<?, ?it/s]
  File "train_classifier.py", line 46, in <module>
    model.train_model(train_df, eval_df = test_df, show_running_loss=False, acc=accuracy_score)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py", line 256, in train_model
    **kwargs,
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py", line 346, in train
    outputs = model(**inputs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/simpletransformers/classification/transformer_models/roberta_model.py", line 80, in forward
    loss = loss_fct(logits.view(-1, self.num_labels), labels.view(-1))
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 916, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1995, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1824, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Assertion `THCTensor_(checkGPU)(state, 5, input, target, weights, output, total_weight)' failed. Some of weight/gradient/input tensors are located on different GPUs. Please move them to a single one. at /pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu:24
```

I have seen a previous issue posted about getting an error with multiple GPUs when the running loss is displayed, but even with `show_running_loss=False`, this error is occurring. My guess is that something is breaking when it comes time to compute the loss? Any ideas?

**Comment by andronovhopf** [comment]
A few other notes: I am using torch 1.2.0

**Comment by ThilinaRajapakse** [comment]
Thank you!

Can you tell me which model you are using? Also, are you using the class weights option?

**Comment by andronovhopf** [comment]
I tried using bert & roberta. I did use the class weights option (although,
I am not positive I'm doing it right- I'm entering a list [x0, x1] where x0
and x1 are the weights for class 0 and 1 respectively. But I'm not sure,
since the weights aren't provided as a a dictionary, if PyTorch
"understands" that the first entry maps to class 0 and the second to class
1).

**Comment by ThilinaRajapakse** [comment]
You are doing it right. That's how the weights are passed to the model. I'm getting the same error when using class weights with multi-gpu training as well. I'm looking into it but haven't found the issue yet. In the meantime, you should be able to run it as long as you don't use class weights.

**Comment by shaanchandra** [comment]
Hi, 
Any update on this? 
It is not working for me either when passing the weight param as `weight = [1,3]` 
I think this is a very basic functionality (pytroch native loss re-weighting, and nothing to do with the library features) that should be addressed on priority?

**Comment by ThilinaRajapakse** [comment]
I didn't get a chance to look into this again. You are free to address it in a pull request if you feel it's a priority though.

**Comment by narendra36** [comment]
Hi @ThilinaRajapakse,
It's a very good library but I'm also getting this error.
Any update on this?

**Comment by flaviussn** [comment]
Same error here :(
