### ISSUE TITLE
'bool' object is not callable in ClassificationModel

### ISSUE THREAD

**Issue by ErikTromp** [ThilinaRajapakse/simpletransformers#248]
I am trying to run a normal ClassificationModel on BERT since multilabel so far isn't paying off. I started training the model with evaluation during training and then got the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\me\Anaconda3\lib\site-packages\simpletransformers\classification\classification_model.py", line 274, in train_model
    **kwargs,
  File "C:\Users\me\Anaconda3\lib\site-packages\simpletransformers\classification\classification_model.py", line 486, in train
    eval_df, verbose=verbose and args["evaluate_during_training_verbose"], silent=True, **kwargs
  File "C:\Users\me\Anaconda3\lib\site-packages\simpletransformers\classification\classification_model.py", line 549, in eval_model
    eval_df, output_dir, multi_label=multi_label, verbose=verbose, silent=silent, **kwargs
  File "C:\Users\me\Anaconda3\lib\site-packages\simpletransformers\classification\classification_model.py", line 666, in evaluate
    result, wrong = self.compute_metrics(preds, out_label_ids, eval_examples, **kwargs)
  File "C:\Users\me\Anaconda3\lib\site-packages\simpletransformers\classification\classification_model.py", line 791, in compute_metrics
    extra_metrics[metric] = func(labels, preds)
TypeError: 'bool' object is not callable
```

**Comment by ThilinaRajapakse** [comment]
Can you show me the code? Are you paying in any additional metrics?

**Comment by ErikTromp** [comment]
No I'm not, here's my code

```
import pandas as pd
from sklearn.model_selection import train_test_split
from simpletransformers.classification import MultiLabelClassificationModel, ClassificationModel
from transformers import RobertaTokenizer, RobertaForSequenceClassification
from transformers import BertTokenizer, BertModel

df = pd.read_csv("data_multiclass_classed.csv", encoding="utf8", delimiter=";")
ttrain_df, validation_df = train_test_split(df, test_size=0.1, random_state=123456)
train_df, eval_df = train_test_split(ttrain_df, test_size=0.3, random_state=123456)

model = ClassificationModel('bert', 'bert-base-dutch-cased', num_labels=47, use_cuda=True, args={'train_batch_size':8, 'gradient_accumulation_steps':16, 'learning_rate': 1e-6, 'num_train_epochs': 4, 'max_seq_length': 256, 'fp16': False, 'reprocess_input_data': True, 'use_cached_eval_features': True, 'evaluate_during_training': True, 'evaluate_during_training_verbose': True, 'output_dir': 'outputs_bert', 'overwrite_output_dir': True})
model.train_model(train_df, eval_df=eval_df, auto_weights=True)

```

**Comment by ThilinaRajapakse** [comment]
`auto_weights` feature is only implemented for multi-modal classification atm. That is causing the issue.

**Comment by ErikTromp** [comment]
Ah didn't know... I also tried it out in multiclass where it worked without this error. Closing ticket.

**Comment by seyonechithrananda** [comment]
Tried to remove auto_weights, but the issue is still occurring. Any thoughts?

**Comment by Adel-Memariani** [comment]
Same issue, After removing 'auto_weights', the problem is still there. I appreciate it if someone can help!
