### ISSUE TITLE
cannot import name 'get_linear_schedule_with_warmup' from 'transformers'

### ISSUE THREAD

**Issue by Adrizzledefizzle** [ThilinaRajapakse/simpletransformers#261]
**Describe the bug**
Cant import 'get_linear_schedule_with_warmup'.

**To Reproduce**

Followed the repo instructions and tried to run example "binary_classification" ( did not work on others a well though) - I think I got all the libraries neede? 

**Desktop (please complete the following information):**
 - Windows 10

**ErrorMsg**
```
runfile('C:/Users/ga2943/Masterthesis Adrian/Code/simpletransformers/simpletransformers-master/examples/text_classification/binary_classification.py', wdir='C:/Users/ga2943/Masterthesis Adrian/Code/simpletransformers/simpletransformers-master/examples/text_classification')
Traceback (most recent call last):

  File "<ipython-input-12-065f3234dc58>", line 1, in <module>
    runfile('C:/Users/ga2943/Masterthesis Adrian/Code/simpletransformers/simpletransformers-master/examples/text_classification/binary_classification.py', wdir='C:/Users/ga2943/Masterthesis Adrian/Code/simpletransformers/simpletransformers-master/examples/text_classification')

  File "C:\Users\ga2943\AppData\Local\Continuum\anaconda3\envs\Envneu\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\ga2943\AppData\Local\Continuum\anaconda3\envs\Envneu\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/ga2943/Masterthesis Adrian/Code/simpletransformers/simpletransformers-master/examples/text_classification/binary_classification.py", line 1, in <module>
    from simpletransformers.classification import ClassificationModel

  File "C:\Users\ga2943\AppData\Local\Continuum\anaconda3\envs\Envneu\lib\site-packages\simpletransformers\classification\__init__.py", line 1, in <module>
    from simpletransformers.classification.classification_model import ClassificationModel

  File "C:\Users\ga2943\AppData\Local\Continuum\anaconda3\envs\Envneu\lib\site-packages\simpletransformers\classification\classification_model.py", line 32, in <module>
    from transformers import AdamW, get_linear_schedule_with_warmup

ImportError: cannot import name 'get_linear_schedule_with_warmup' from 'transformers' (C:\Users\ga2943\AppData\Local\Continuum\anaconda3\envs\Envneu\lib\site-packages\transformers\__init__.py)
```

How do I solve this?

**Comment by Adrizzledefizzle** [comment]
My transformers version is 2.1.1 as I just found out, is that the issue here?

**Comment by ThilinaRajapakse** [comment]
Yes, that is the likely issue. Did you get this error when trying to install it in a fresh environment?

**Comment by Adrizzledefizzle** [comment]
Yes I did. And I can not change my version.. Why does it say 2.1.1 in spyder but the errormsg and cmd prompt says 2.5.1 ?

**Comment by Adrizzledefizzle** [comment]
I could resolve it by updating it to 2.3.0. Now it gives me a new error I can not manage to solve for hours. Ill open a new issue for it
