### ISSUE TITLE
RuntimeError when trying to import ClassificationModel

### ISSUE THREAD

**Issue by MaxGniluynehc** [ThilinaRajapakse/simpletransformers#289]
I am using Windows 10, pycharm with anaconda3.

When ever I run this:
`from simpletransformers.classification import ClassificationModel`

I received this `RuntimeError`:

Traceback (most recent call last):
  File "C:\Users\maxch\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-23-e269f817f0ec>", line 1, in <module>
    from simpletransformers.classification import ClassificationModel
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\maxch\Anaconda3\lib\site-packages\simpletransformers\classification\__init__.py", line 1, in <module>
    from simpletransformers.classification.classification_model import ClassificationModel
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\maxch\Anaconda3\lib\site-packages\simpletransformers\classification\classification_model.py", line 56, in <module>
    from simpletransformers.classification.classification_utils import (
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\maxch\Anaconda3\lib\site-packages\simpletransformers\classification\classification_utils.py", line 34, in <module>
    import torchvision
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\maxch\Anaconda3\lib\site-packages\torchvision\__init__.py", line 3, in <module>
    from torchvision import models
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\maxch\Anaconda3\lib\site-packages\torchvision\models\__init__.py", line 12, in <module>
    from . import detection
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\maxch\Anaconda3\lib\site-packages\torchvision\models\detection\__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\maxch\Anaconda3\lib\site-packages\torchvision\models\detection\faster_rcnn.py", line 13, in <module>
    from .rpn import AnchorGenerator, RPNHead, RegionProposalNetwork
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\maxch\Anaconda3\lib\site-packages\torchvision\models\detection\rpn.py", line 11, in <module>
    from . import _utils as det_utils
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\maxch\Anaconda3\lib\site-packages\torchvision\models\detection\_utils.py", line 19, in <module>
    class BalancedPositiveNegativeSampler(object):
  File "C:\Users\maxch\Anaconda3\lib\site-packages\torch\jit\__init__.py", line 1219, in script
    Example (an exported and ignored method in a module)::
  File "C:\Users\maxch\Anaconda3\lib\site-packages\torch\jit\__init__.py", line 1076, in _compile_and_register_class
    return mod._overloads.get(field, None) if isinstance(mod, ScriptModule) else None
RuntimeError: class '__torch__.torchvision.models.detection._utils.BalancedPositiveNegativeSampler' already defined. (register_type at C:\Users\builder\AppData\Local\Temp\pip-req-build-9msmi1s9\torch/csrc/jit/script/compilation_unit.h:166)
(no backtrace available)

Any one could help? Thanks in advance!

**Comment by ThilinaRajapakse** [comment]
Looks like PyTorch wasn't installed correctly in your environment. Please try creating a new environment and installing the packages again with the steps given in the readme.

**Comment by MaxGniluynehc** [comment]
Thank you for your reply. I found that I can import `torch` but not `pytorch` in pycharm. Will this be sufficient to use `simpletransformers`? And no error is reported if I simply run `import simpletransformers`. But if I proceed and run `simpletransformers.classification`, it returns `simpletransformers has no attribute classification`...

**Comment by ThilinaRajapakse** [comment]
PyTorch is imported using the name `torch` so that's expected. You do need to be able to import `simpletransformers.classification` though. If it can't find `classification`, that means the `simpletransformers` being imported is not the correct library (possibly something on your local drive with the same name).

**Comment by MaxGniluynehc** [comment]
I tried to rebuild the environment and followed the code to install all the necessary packages. But it returns the following error:

Traceback (most recent call last):
  File "C:\Users\maxch\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-e269f817f0ec>", line 1, in <module>
    from simpletransformers.classification import ClassificationModel
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\maxch\Anaconda3\lib\site-packages\simpletransformers\classification\__init__.py", line 1, in <module>
    from simpletransformers.classification.classification_model import ClassificationModel
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\maxch\Anaconda3\lib\site-packages\simpletransformers\classification\classification_model.py", line 56, in <module>
    from simpletransformers.classification.classification_utils import (
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\maxch\Anaconda3\lib\site-packages\simpletransformers\classification\classification_utils.py", line 34, in <module>
    import torchvision
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\maxch\Anaconda3\lib\site-packages\torchvision\__init__.py", line 3, in <module>
    from torchvision import models
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\maxch\Anaconda3\lib\site-packages\torchvision\models\__init__.py", line 12, in <module>
    from . import detection
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\maxch\Anaconda3\lib\site-packages\torchvision\models\detection\__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\maxch\Anaconda3\lib\site-packages\torchvision\models\detection\faster_rcnn.py", line 13, in <module>
    from .rpn import AnchorGenerator, RPNHead, RegionProposalNetwork
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\maxch\Anaconda3\lib\site-packages\torchvision\models\detection\rpn.py", line 11, in <module>
    from . import _utils as det_utils
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\maxch\Anaconda3\lib\site-packages\torchvision\models\detection\_utils.py", line 19, in <module>
    class BalancedPositiveNegativeSampler(object):
  File "C:\Users\maxch\Anaconda3\lib\site-packages\torch\jit\__init__.py", line 1219, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "C:\Users\maxch\Anaconda3\lib\site-packages\torch\jit\__init__.py", line 1076, in _compile_and_register_class
    _jit_script_class_compile(qualified_name, ast, rcb)
  File "C:\Users\maxch\Anaconda3\lib\site-packages\torch\jit\_recursive.py", line 222, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "C:\Users\maxch\Anaconda3\lib\site-packages\torch\jit\__init__.py", line 1226, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
RuntimeError: 
builtin cannot be used as a value:
at C:\Users\maxch\Anaconda3\lib\site-packages\torchvision\models\detection\_utils.py:14:56
def zeros_like(tensor, dtype):
    # type: (Tensor, int) -> Tensor
    return torch.zeros_like(tensor, dtype=dtype, layout=tensor.layout,
                                                        ~~~~~~~~~~~~~ <--- HERE
                            device=tensor.device, pin_memory=tensor.is_pinned())
'zeros_like' is being compiled since it was called from '__torch__.torchvision.models.detection._utils.BalancedPositiveNegativeSampler.__call__'
at C:\Users\maxch\Anaconda3\lib\site-packages\torchvision\models\detection\_utils.py:72:12
            # randomly select positive and negative examples
            perm1 = torch.randperm(positive.numel(), device=positive.device)[:num_pos]
            perm2 = torch.randperm(negative.numel(), device=negative.device)[:num_neg]
            pos_idx_per_image = positive[perm1]
            neg_idx_per_image = negative[perm2]
            # create binary mask from indices
            pos_idx_per_image_mask = zeros_like(
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~...  <--- HERE
                matched_idxs_per_image, dtype=torch.uint8
            )
            neg_idx_per_image_mask = zeros_like(
                matched_idxs_per_image, dtype=torch.uint8
            )
            pos_idx_per_image_mask[pos_idx_per_image] = torch.tensor(1, dtype=torch.uint8)
            neg_idx_per_image_mask[neg_idx_per_image] = torch.tensor(1, dtype=torch.uint8)


I suspect that when installing the package, I used the `conda install` for the transformers and all the prerequisites and `pip install` for the simpletransformers, and these 2 methods restore the packages in different places on my laptop. So, when I build my python environment with anaconda, I cannot import the package that installed by pip. Will this be a matter? If so, can I install simpletransformers via `conda`? Or how can I deal with this?

**Comment by ThilinaRajapakse** [comment]
I wouldn't expect that to cause an issue but it's hard to say. You can follow the instructions [here](https://github.com/ThilinaRajapakse/simpletransformers#with-conda) and it should install without any issue.

I think the issue is likely with your PyTorch installation (perhaps the version is outdated) rather than simpletransformers/transformers.
