### ISSUE TITLE
ImportError: cannot import name 'XLMRobertaConfig

### ISSUE THREAD

**Issue by simepy** [ThilinaRajapakse/simpletransformers#305]
**Describe the bug**
```
Traceback (most recent call last):
  File "NER.py", line 1, in <module>
    from simpletransformers.ner import NERModel
  File "/usr/lib/python3.7/site-packages/simpletransformers/ner/__init__.py", line 1, in <module>
    from simpletransformers.ner.ner_model import NERModel
  File "/usr/lib/python3.7/site-packages/simpletransformers/ner/ner_model.py", line 36, in <module>
    from transformers import (
ImportError: cannot import name 'XLMRobertaConfig' from 'transformers' (/usr/lib/python3.7/site-packages/transformers/__init__.py)
```

**To Reproduce**
```
from simpletransformers.ner import NERModel

model = NERModel('camembert', 'camembert-base', use_cuda=False, args={'overwrite_output_dir': True, 'reprocess_input_data': True})

predictions, raw_outputs = model.predict(["Your text"])

```

**Expected behavior**
model.predict result

**Desktop (please complete the following information):**
 - OS: Archlinux 5.5.13-arch2-1
 - SimpleTransformer version : 0.24.0

**Comment by ThilinaRajapakse** [comment]
This script isn't throwing an error for me. Is your Transformers library up to date?

**Comment by Pradhy729** [comment]
Update to transformers v2.8.0 for XLMRoberta

**Comment by simepy** [comment]
Thanks, before I did, however "pip install -U simpletransformers"
