### ISSUE TITLE
Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.

### ISSUE THREAD

**Issue by shashi792** [ThilinaRajapakse/simpletransformers#322]
**Describe the bug**
```
therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:/Users/abc/PycharmProjects/ABCD/classify.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\abc\Anaconda_Envs\abc_env\lib\site-packages\pandas\__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.8 from "C:\Users\Shashishekar.R\Anaconda_Envs\calculationInContracts_env\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.
```

**Additional context**
Upon following the [](https://github.com/ThilinaRajapakse/simpletransformers#minimal-start-for-binary-classification). The package installation was also done as provided in the README file. Can you provide the version numbers for packages ?

**Comment by ThilinaRajapakse** [comment]
You can use the latest version of the packages.

It looks like your conda environment got messed up somehow. Do you still get this error if you install in a fresh environment?

**Comment by shashi792** [comment]
I solved it. It was indeed the conda issue. Installing numpy via conda was causing the issue. From StackOverflow forum, it was discussed that conda installation of numpy 1.8.1 had some issues (not the same one, but related issues)

Uninstalled numpy and pandas, then installed them back again using.
```
pip install --upgrade numpy
pip install --upgrade pandas
```
Not sure, what changed with this installation. But, it started working.
