### ISSUE TITLE
How to set the args so that I can use multiple gpu to train?

### ISSUE THREAD

**Issue by ForLittleBeauty** [ThilinaRajapakse/simpletransformers#333]
For example
there are 6 GPUS 0,1,2,3,4,5,6
and 3,4 are available
How should I write the code to train my data on both of them? I can no find this in readme.md
thank you very much

**Comment by ThilinaRajapakse** [comment]
```
import os


os.environ['CUDA_VISIBLE_DEVICES'] = ["3", "4"]

model = ClassificationModel("bert", "bert-base-cased", args={"n_gpu": 2})
```

This should work. Let me know if you run into issues.

**Comment by ForLittleBeauty** [comment]
@ThilinaRajapakse thank you a lot, 
and I find that it should be like this:
os.environ['CUDA_VISIBLE_DEVICES'] = "3,4"
it needs a string instead of a list.
However, when training, a new error comes out,
Here is the message:

Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ModuleNotFoundError("No module named 'amp_C'",)
Epoch:   0%|                                                                                                                                                                                | 0/1 [00:00<?, ?it/sTraceback (most recent call last):                                                                                                                                                         | 0/515 [00:00<?, ?it/s]
  File "main.py", line 38, in <module>
    main()
  File "main.py", line 35, in main
    result,_,_ =     train_eval(train_df,eval_df)
  File "main.py", line 28, in train_eval
    model.train_model(train_df)
  File "/home/ugrad/.conda/envs/transNLP/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py", line 265, in train_model
    **kwargs,
  File "/home/ugrad/.conda/envs/transNLP/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py", line 384, in train
    outputs = model(**inputs)
  File "/home/ugrad/.conda/envs/transNLP/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ugrad/.conda/envs/transNLP/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ugrad/.conda/envs/transNLP/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ugrad/.conda/envs/transNLP/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/ugrad/.conda/envs/transNLP/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
**StopIteration: Caught StopIteration in replica 0 on device 0.**
Original Traceback (most recent call last):
  File "/home/ugrad/.conda/envs/transNLP/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/ugrad/.conda/envs/transNLP/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ugrad/.conda/envs/transNLP/lib/python3.6/site-packages/simpletransformers/classification/transformer_models/xlnet_model.py", line 72, in forward
    head_mask=head_mask,
  File "/home/ugrad/.conda/envs/transNLP/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ugrad/.conda/envs/transNLP/lib/python3.6/site-packages/transformers/modeling_xlnet.py", line 761, in forward
    dtype_float = next(self.parameters()).dtype
**StopIteration**


is it the problem of my installing of apex package?

**Comment by ThilinaRajapakse** [comment]
Possibly. Can you try running with fp16 off?

**Comment by ForLittleBeauty** [comment]
No, even if I set
'fp16':False in args
the same error comes out

**Comment by ThilinaRajapakse** [comment]
Does it work if you only use a single GPU? Also, what is the batch size you are using?

**Comment by ForLittleBeauty** [comment]
Yeah, when using a single GPU, everything is all right.
my batch is 4 or 8

**Comment by ThilinaRajapakse** [comment]
There does seem to be an issue with your apex installation, but I don't think that is causing this issue.

Can you try using another model like BERT or RoBERTa? Trying to see if it's specific to XLNet.
