### ISSUE TITLE
multiprocessing for Windows - set limit on number of workers

### ISSUE THREAD

**Issue by leungi** [ThilinaRajapakse/simpletransformers#401]
**Describe the bug**
On Windows OS, the number of workers for multiprocessing is limited to 63, and there isn't a check in `simpletransformers` to limit this, hence creating error.

**To Reproduce**

1. run [language model - minimal example](https://github.com/ThilinaRajapakse/simpletransformers#language-model-training).

**Expected behavior**
Expect model to train without error.

**Screenshots**
```python
INFO:simpletransformers.language_modeling.language_modeling_utils: Creating features from dataset file at cache_dir/
  0%|          | 0/23767 [00:00<?, ?it/s]Thread-6:
Traceback (most recent call last):
  File "D:\Continuum\anaconda3\envs\simpletransformers\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\Continuum\anaconda3\envs\simpletransformers\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Continuum\anaconda3\envs\simpletransformers\lib\multiprocessing\pool.py", line 519, in _handle_workers
    cls._wait_for_updates(current_sentinels, change_notifier)
  File "D:\Continuum\anaconda3\envs\simpletransformers\lib\multiprocessing\pool.py", line 499, in _wait_for_updates
    wait(sentinels, timeout=timeout)
  File "D:\Continuum\anaconda3\envs\simpletransformers\lib\multiprocessing\connection.py", line 878, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "D:\Continuum\anaconda3\envs\simpletransformers\lib\multiprocessing\connection.py", line 810, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 88
```

**Desktop (please complete the following information):**
```
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
```

**Additional context**
Known behaviour seen in other libraries as well; workaround is to limit workers when Windows OS is detected, as per this reference - psf/black/pull/838

**Suggestion**
Adapting from reference above, In `process_count` args, add conditional:

```python
if sys.platform == "win32":
  process_count= cpu_count() - 2 if cpu_count() > 2 else 1
  process_count= min(process_count, 61)
```

**Comment by ThilinaRajapakse** [comment]
Thanks! I'll add this to `global_args`. In the meantime, the `process_count` can be set manually as well.

**Comment by leungi** [comment]
Many thanks for this useful library 🙏

**Comment by lanetao** [comment]
ths for this solution
