### ISSUE TITLE
NameError: name 'wandb' is not defined

### ISSUE THREAD

**Issue by ximo1984** [ThilinaRajapakse/simpletransformers#409]
**Describe the bug**
When try to train a classification model with wandb I get this error in google colab.

_Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/wandb_agent.py", line 64, in _start
    function()
  File "<ipython-input-8-9419ea4c148f>", line 19, in trainMultiClass
    f1=f1_multiclass, acc=accuracy_score)
  File "/usr/local/lib/python3.6/dist-packages/simpletransformers/classification/classification_model.py", line 269, in train_model
    **kwargs,
  File "/usr/local/lib/python3.6/dist-packages/simpletransformers/classification/classification_model.py", line 373, in train
    wandb.init(project=args["wandb_project"], config={**args}, **args["wandb_kwargs"])
NameError: name 'wandb' is not defined_

**To Reproduce**
```
import wandb
sweep_config = {
    'method': 'bayes', #grid, random, bayes
    'metric': {
      'name': 'eval_loss',
      'goal': 'minimize'   
    },
    'parameters': {  
        'learning_rate': {
            'values': [ 5e-5, 3e-5, 4e-5, 2e-5] #4e-5
        },
        'epochs': {
            'values': [1, 2] #2
        },
        'max_seq_length': { #174
            'min': 128,
            'max': 200
        },
        'train_batch_size': {
            'values': [8, 16, 32] #16
        },
        'warmup_ratio': { #0.07478
            'min': 0.04,
            'max': 0.08
        },
        'warmup_steps': {
            'min': 0,
            'max': 100,
        }
    }
}

sweep_id = wandb.sweep(sweep_config,project="sectors")

def f1_multiclass(labels, preds):
    return f1_score(labels, preds, average='micro')

def trainMultiClass():
  wandb.init()
  print("HyperParams=>>", wandb.config)
  num_labels = len(sector_to_id.keys())
  model = ClassificationModel('bert', 'bert-base-uncased', num_labels=11)
  model.train_model(train, output_dir='bert-uncased-sector', eval_df=test, args={'overwrite_output_dir': True, 
                                                                   'num_train_epochs': wandb.config.epochs,
                                                                   'learning_rate': wandb.config.learning_rate,
                                                                   'wandb_project': "sectors",
                                                                   'evaluate_during_training': True,
                                                                   'evaluate_during_training_steps': 100,
                                                                   'max_seq_length': wandb.config.max_seq_length,
                                                                   'train_batch_size': wandb.config.train_batch_size,
                                                                   'warmup_ratio': wandb.config.warmup_ratio,
                                                                   'warmup_steps': wandb.config.warmup_steps},
                    f1=f1_multiclass, acc=accuracy_score)

wandb.agent(sweep_id,function=trainMultiClass)

```
**Expected behavior**
Four days ago it worked perfectly I didn't get any error.

**Desktop (please complete the following information):**
 - Google colab

**Comment by ThilinaRajapakse** [comment]
Does this script work if you use an earlier version of simple transformers?

**Comment by ximo1984** [comment]
Now it's working again. I don't know if wandb changed something or I made a mistake because I had had two times "from simpletransformers.classification import ClassificationModel".

Thanks for your excellent library.

**Comment by ThilinaRajapakse** [comment]
It was probably something temporary with colab or wandb then.

**Comment by ximo1984** [comment]
Sorry but it happened again. I try with version of simpletransformers 0.28.8 and It works perfect.

**Comment by ThilinaRajapakse** [comment]
Just tried your script locally and it works for me (as far as the wandb setup goes). My own minimal sweep script works fine as well.

```python
import wandb
import logging

import sklearn

import pandas as pd
from simpletransformers.classification import ClassificationModel


sweep_config = {
    "method": "random",  # grid, random
    "metric": {"name": "train_loss", "goal": "minimize"},
    "parameters": {"num_train_epochs": {"values": [10, 2, 5]}},
}

sweep_id = wandb.sweep(sweep_config, project="sweep_test")


def train():
    logging.basicConfig(level=logging.INFO)
    transformers_logger = logging.getLogger("transformers")
    transformers_logger.setLevel(logging.WARNING)
    # Train and Evaluation data needs to be in a Pandas Dataframe of two columns. The first column is the text with type str, and the second column in the label with type int.
    train_data = [
        ["Example sentence belonging to class 1" , 1],
    ]

    train_data.extend([["More sentences", 0] for i in range(10)])
    train_data.extend([["More sentences 1", 1] for i in range(10)])

    train_df = pd.DataFrame(train_data, columns=["text", "labels"])

    eval_data = [["Example eval sentence belonging to class 1", 1], ["A weirdly different one", 0]]
    eval_df = pd.DataFrame(eval_data)

    model_args = {
        "reprocess_input_data": True,
        "overwrite_output_dir": True,
        "num_train_epochs": 1,
        "wandb_project": "sweep_test",

        "early_stopping_metric": "mcc",

        "manual_seed": 4,
        "use_multiprocessing": True,
        "train_batch_size": 16,
        "eval_batch_size": 8,
        "learning_rate": 4e-4,
    }

    wandb_config = {
        "num_train_epochs": 1
    }

    # Initialize a new wandb run
    wandb.init(config=wandb_config)

    # Config is a variable that holds and saves hyperparameters and inputs
    wandb_config = wandb.config

    sweep_values = {key: value["value"] for key, value in wandb_config.as_dict().items() if key != "_wandb"}

    model_args.update(sweep_values)

    # Create a TransformerModel
    model = ClassificationModel("roberta", "roberta-base", use_cuda=False, args=model_args, num_labels=10)
    # print(train_df.head())

    # Train the model
    model.train_model(train_df, eval_df=eval_df)


wandb.agent(sweep_id, train)

```

**Comment by ximo1984** [comment]
Maybe its a temporally error with colab or wandb. 
Thanks for your help.
