### ISSUE TITLE
RuntimeError: expected dtype Float but got dtype Long

### ISSUE THREAD

**Issue by siamakz** [ThilinaRajapakse/simpletransformers#454]
I am following your [tutorial](https://medium.com/swlh/solving-sentence-pair-tasks-using-simple-transformers-2496fe79d616) but on Quora Question Pair dataset. But I am getting the following error:

> Traceback (most recent call last):
  File "/Users/sia/Desktop/NLP/SimpleTransformers_QQP.py", line 40, in <module>
    model.train_model(train_df, eval_df=val_df, f1=f1_score, acc=accuracy_score)
  File "/Users/sia/Desktop/NLP/venv/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py", line 285, in train_model
    **kwargs,
  File "/Users/sia/Desktop/NLP/venv/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py", line 423, in train
    loss.backward()
  File "/Users/sia/Desktop/NLP/venv/lib/python3.6/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/Users/sia/Desktop/NLP/venv/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: expected dtype Float but got dtype Long
>

I am using the latest versions of both transformers (2.11.0) and simple transformers (0.32.3) and torch version (1.4.0).

and here is the part of code:

    train_args = {
        "fp16": False,
        'reprocess_input_data': True,
        'overwrite_output_dir': True,
        'evaluate_during_training': True,
        'max_seq_length': 100,
        'num_train_epochs': 1,
        "n_gpu": 0,
        'evaluate_during_training_steps': 50,
        'train_batch_size': 5,}

    model = ClassificationModel('roberta', 'roberta-base', num_labels=1, args=train_args, use_cuda=False)

    model.train_model(train_df, eval_df=val_df, f1=f1, acc=acc)

Can you please share your thought with me?

**Comment by siamakz** [comment]
setting num_labels=2 fixed the issue!
