### ISSUE TITLE
Language model training using Roberta

### ISSUE THREAD

**Issue by anindabitm** [ThilinaRajapakse/simpletransformers#526]
**Error generation when doing language model finetuning**
Full error report below

```
---> 25 model.train_model(train_file)

8 frames
/usr/local/lib/python3.6/dist-packages/simpletransformers/language_modeling/language_modeling_model.py in train_model(self, train_file, output_dir, show_running_loss, args, eval_file, verbose, **kwargs)
    381             eval_file=eval_file,
    382             verbose=verbose,
--> 383             **kwargs,
    384         )
    385 

/usr/local/lib/python3.6/dist-packages/simpletransformers/language_modeling/language_modeling_model.py in train(self, train_dataset, output_dir, show_running_loss, eval_file, verbose, **kwargs)
    519             train_iterator.set_description(f"Epoch {epoch_number + 1} of {args.num_train_epochs}")
    520             for step, batch in enumerate(
--> 521                 tqdm(train_dataloader, desc=f"Running Epoch {epoch_number}", disable=args.silent)
    522             ):
    523                 if steps_trained_in_current_epoch > 0:

/usr/local/lib/python3.6/dist-packages/tqdm/notebook.py in __iter__(self, *args, **kwargs)
    213     def __iter__(self, *args, **kwargs):
    214         try:
--> 215             for obj in super(tqdm_notebook, self).__iter__(*args, **kwargs):
    216                 # return super(tqdm...) will not catch exception
    217                 yield obj

/usr/local/lib/python3.6/dist-packages/tqdm/std.py in __iter__(self)
   1102                 fp_write=getattr(self.fp, 'write', sys.stderr.write))
   1103 
-> 1104         for obj in iterable:
   1105             yield obj
   1106             # Update and possibly print the progressbar.

/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py in __next__(self)
    343 
    344     def __next__(self):
--> 345         data = self._next_data()
    346         self._num_yielded += 1
    347         if self._dataset_kind == _DatasetKind.Iterable and \

/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py in _next_data(self)
    383     def _next_data(self):
    384         index = self._next_index()  # may raise StopIteration
--> 385         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    386         if self._pin_memory:
    387             data = _utils.pin_memory.pin_memory(data)

/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     42     def fetch(self, possibly_batched_index):
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:
     46             data = self.dataset[possibly_batched_index]

/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py in <listcomp>(.0)
     42     def fetch(self, possibly_batched_index):
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:
     46             data = self.dataset[possibly_batched_index]

/usr/local/lib/python3.6/dist-packages/simpletransformers/language_modeling/language_modeling_utils.py in __getitem__(self, item)
    132 
    133     def __getitem__(self, item):
--> 134         return torch.tensor(self.examples[item], dtype=torch.long)
    135 
    136 

TypeError: an integer is required (got type NoneType)
```

**To reproduce:**
```python
from simpletransformers.language_modeling import LanguageModelingModel
import logging
logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)

train_args = {
    "reprocess_input_data": True,
    "overwrite_output_dir": True,
    "fp16":False,
    "mlm":True,
    "output_dir": "outputs_model/",
}

train_file = "lm.txt"
model = LanguageModelingModel('roberta','roberta-base',args=train_args)
model.train_model(train_file)
```

Expected behavior
Language model fine-tuning should happen smoothly

Colaboratory from Google

**Comment by ThilinaRajapakse** [comment]
Might be a silly question, but do you have a non-empty `lm.txt` file in the root directory of your project?

**Comment by anindabitm** [comment]
No. I checked the file lm.txt is not empty. Sorry to have missed this. In fact if I use best model, the training is done smoothly

**Comment by ujwal-narayan** [comment]
Hi, 
I'm getting a similar error. bert trains fine but when I switch to roberta  the error, `TypeError: an integer is required (got type NoneType)`  pops up. 
I'm training roberta from scratch and my simpletransformers version is `0.47.2`.
Is there anything I can do to fix this?

Thanks!


Attaching my error message here 
```
Running Epoch 0 of 1:   0
Epoch 1 of 1:   0%| | 0/1
Traceback (most recent call last):
  File "train.py", line 47, in <module>
    model.train_model(train_file, eval_file=valid_file)
  File "/home/badwolf/miniconda3/envs/transformer/lib/python3.8/site-packages/simpletransformers/language_modeling/language_modeling_model.py", line 364, in train_model
    global_step, tr_loss = self.train(
  File "/home/badwolf/miniconda3/envs/transformer/lib/python3.8/site-packages/simpletransformers/language_modeling/language_modeling_model.py", line 555, in train
    for step, batch in enumerate(batch_iterator):
  File "/home/badwolf/miniconda3/envs/transformer/lib/python3.8/site-packages/tqdm/std.py", line 1130, in __iter__
    for obj in iterable:
  File "/home/badwolf/miniconda3/envs/transformer/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/badwolf/miniconda3/envs/transformer/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/badwolf/miniconda3/envs/transformer/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line
wandb: Waiting for W&B process to finish, PID 10764
 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/badwolf/miniconda3/envs/transformer/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/badwolf/miniconda3/envs/transformer/lib/python3.8/site-packages/simpletransformers/language_modeling/language_modeling_utils.py", line 132, in __getitem__
    return torch.tensor(self.examples[item], dtype=torch.long)
TypeError: an integer is required (got type NoneType)
```

**Comment by ThilinaRajapakse** [comment]
I can't reproduce this. It's running fine with the provided code for me (locally). Is this Colab specific?

**Comment by ujwal-narayan** [comment]
Hi,
Sorry for the late reply.  It's local, and not Colab specific.
