### ISSUE TITLE
Error in model.predict pretrained as regression

### ISSUE THREAD

**Issue by ZotovaElena** [ThilinaRajapakse/simpletransformers#564]
**Describe the bug**
The function model.predict returns an error when assigning a label. The model is fine-tuned as regression. 

Traceback (most recent call last):
  File "prueba.py", line 72, in <module>
    predictions, outputs = model.predict(eval_df.text.to_list())
  File "/home/ezotova/simple_transformers/lib/python3.7/site-packages/                                simpletransformers/classification/classification_model.py", line 1158, in predic                                t
    preds = [inverse_labels_map[pred] for pred in preds]
  File "/home/ezotova/simple_transformers/lib/python3.7/site-packages/                                simpletransformers/classification/classification_model.py", line 1158, in <listc                                omp>
    preds = [inverse_labels_map[pred] for pred in preds]
KeyError: 0.44720975

**To Reproduce**
```
from simpletransformers.classification import ClassificationModel, ClassificationArgs
 import pandas as pd
import logging

logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)

args={'overwrite_output_dir': True, 
     'reprocess_input_data': True,
     'num_train_epochs': 2,
     'train_batch_size': 16,
      'eval_batch_size': 8,
      'max_seq_length': 230,
      'learning_rate': 2e-5,
      "save_model_every_epoch": True,
      'no_cache': True,
      'do_lower_case': False,
      'use_early_stopping': True,
      'early_stopping_patience': 5,
      'early_stopping_consider_epochs': True,
      'fp16': False, 
      'regression': True,
      'labels_map': False}
      
# Preparing train data
train_data = [
    ["Aragorn was the heir of Isildur", 1.0],
    ["Frodo was the heir of Isildur", 0.0],
    ["Pippin is stronger than Merry", 0.3],
]
train_df = pd.DataFrame(train_data)
train_df.columns = ["text", "labels"]

# Preparing eval data
eval_data = [
    ["Theoden was the king of Rohan", 1.0],
    ["Merry was the king of Rohan", 0.0],
    ["Aragorn is stronger than Boromir", 0.5],
]
eval_df = pd.DataFrame(eval_data)
eval_df.columns = ["text", "labels"]

# Create a ClassificationModel
model = ClassificationModel(
    "bert",
    "bert-base-cased",
    num_labels=1,
    args=args
)

# Train the model
model.train_model(train_df)

# Evaluate the model
result, model_outputs, wrong_predictions = model.eval_model(eval_df)

# Make predictions with the model
predictions, raw_outputs = model.predict(["Sam was a Wizard"])
print(predictions)

model = ClassificationModel('bert', 'outputs/checkpoint-2-epoch-2', num_labels=1, args=args)
print(model.args.labels_map)

predictions, outputs = model.predict(eval_df.text.to_list())
print(predictions)
``` 
**Expected behavior**
Should return a float as a label. 

**Desktop:**
 - OS Ubuntu 

The error is detected after reinstalling Simple Transformers on 25/06/2020, after version 3.0 of Transformers was released. 

Was fixed with the following lines

```
model = ClassificationModel('bert', 'outputs/checkpoint-2-epoch-2', num_labels=1, args=args)
model.args.labels_map = {}
```

**Comment by ThilinaRajapakse** [comment]
Pushed a fix for this (in 0.43.5). Please let me know if it works.
