### ISSUE TITLE
Running binary_classification.py file in example folder fails

### ISSUE THREAD

**Issue by liubest** [ThilinaRajapakse/simpletransformers#625]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    exitcode = _main(fd, parent_sentinel)
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/runpy.py", line 265, in run_path
    main_content = runpy.run_path(main_path,
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/runpy.py", line 87, in _run_code
    return _run_module_code(code, init_globals, run_name,
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/runpy.py", line 97, in _run_module_code
    exec(code, run_globals)
  File "/Volumes/Untitled/simpletransformers/examples/text_classification/binary_classification.py", line 13, in <module>
    _run_code(code, mod_globals, init_globals,
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/runpy.py", line 87, in _run_code
    model = ClassificationModel("roberta", "roberta-base", use_cuda = False)
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/site-packages/simpletransformers/classification/classification_model.py", line 194, in __init__
    exec(code, run_globals)
  File "/Volumes/Untitled/simpletransformers/examples/text_classification/binary_classification.py", line 13, in <module>
    model = ClassificationModel("roberta", "roberta-base", use_cuda = False)
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/site-packages/simpletransformers/classification/classification_model.py", line 187, in __init__
    self.model = model_class.from_pretrained(model_name, config=self.config, **kwargs)
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/site-packages/transformers/modeling_utils.py", line 745, in from_pretrained
    self.tokenizer = tokenizer_class.from_pretrained(model_name, do_lower_case=self.args.do_lower_case, **kwargs)
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1140, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1287, in _from_pretrained
    load(model_to_load, prefix=start_prefix)
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/site-packages/transformers/modeling_utils.py", line 734, in load
    load(child, prefix + name + ".")
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/site-packages/transformers/modeling_utils.py", line 734, in load
    load(child, prefix + name + ".")
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/site-packages/transformers/modeling_utils.py", line 734, in load
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/site-packages/transformers/tokenization_roberta.py", line 159, in __init__
    load(child, prefix + name + ".")
  [Previous line repeated 3 more times]
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/site-packages/transformers/modeling_utils.py", line 729, in load
    module._load_from_state_dict(
    super().__init__(
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/site-packages/transformers/tokenization_gpt2.py", line 175, in __init__
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/site-packages/torch/nn/modules/module.py", line 975, in _load_from_state_dict
    bpe_merges = [tuple(merge.split()) for merge in bpe_merges]
  File "/Users/richard/opt/anaconda3/envs/transformers/lib/python3.8/site-packages/transformers/tokenization_gpt2.py", line 175, in <listcomp>
    bpe_merges = [tuple(merge.split()) for merge in bpe_merges]

**Comment by ThilinaRajapakse** [comment]
It works for me. This looks like a version/OS issue. What are your simple transformers, transformers, tokenizers versions, and your OS?

**Comment by liubest** [comment]
Hi ThilinaRajapakse, Below is my package version, my os is macos Mojave 10.14.6

# Name                    Version                   Build  Channel
blas                      1.0                         mkl
ca-certificates           2020.6.24                     0
certifi                   2020.6.20                py38_0
chardet                   3.0.4                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
configparser              5.0.0                    pypi_0    pypi
cpuonly                   1.0                           0    pytorch
docker-pycreds            0.4.0                    pypi_0    pypi
filelock                  3.0.12                   pypi_0    pypi
gitdb                     4.0.5                    pypi_0    pypi
gitpython                 3.1.7                    pypi_0    pypi
gql                       0.2.0                    pypi_0    pypi
graphql-core              1.1                      pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
idna                      2.10                     pypi_0    pypi
intel-openmp              2019.4                      233
joblib                    0.16.0                   pypi_0    pypi
keras                     2.4.3                    pypi_0    pypi
libcxx                    10.0.0                        1
libedit                   3.1.20191231         h1de35cc_1
libffi                    3.3                  hb1e8313_2
mkl                       2019.4                      233
mkl-service               2.3.0            py38hfbe908c_0
mkl_fft                   1.1.0            py38hc64f4ea_0
mkl_random                1.1.1            py38h959d312_0
ncurses                   6.2                  h0a44026_1
ninja                     1.10.0           py38h879752b_0
numpy                     1.19.1           py38h3b9f5b6_0
numpy-base                1.19.1           py38hcfb5961_0
nvidia-ml-py3             7.352.0                  pypi_0    pypi
openssl                   1.1.1g               h1de35cc_0
packaging                 20.4                     pypi_0    pypi
pandas                    1.0.5            py38h959d312_0
pathtools                 0.1.2                    pypi_0    pypi
pip                       20.1.1                   py38_1
promise                   2.3                      pypi_0    pypi
protobuf                  3.12.4                   pypi_0    pypi
psutil                    5.7.2                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.8.5                h26836e1_1
python-dateutil           2.8.1                      py_0
pytorch                   1.6.0                   py3.8_0    pytorch
pytz                      2020.1                     py_0
pyyaml                    5.3.1                    pypi_0    pypi
readline                  8.0                  h1de35cc_0
regex                     2020.7.14                pypi_0    pypi
requests                  2.24.0                   pypi_0    pypi
sacremoses                0.0.43                   pypi_0    pypi
scikit-learn              0.23.2                   pypi_0    pypi
scipy                     1.5.2                    pypi_0    pypi
sentencepiece             0.1.91                   pypi_0    pypi
sentry-sdk                0.16.3                   pypi_0    pypi
seqeval                   0.0.12                   pypi_0    pypi
setuptools                49.2.0                   py38_0
shortuuid                 1.0.1                    pypi_0    pypi
simpletransformers        0.46.6                   pypi_0    pypi
six                       1.15.0                     py_0
smmap                     3.0.4                    pypi_0    pypi
sqlite                    3.32.3               hffcf06c_0
subprocess32              3.5.4                    pypi_0    pypi
tensorboardx              2.1                      pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.10               hb0a8c7a_0
tokenizers                0.8.1                    pypi_0    pypi
tqdm                      4.47.0                     py_0
transformers              3.0.2                    pypi_0    pypi
urllib3                   1.25.10                  pypi_0    pypi
wandb                     0.9.4                    pypi_0    pypi
watchdog                  0.10.3                   pypi_0    pypi
wheel                     0.34.2                   py38_0
xz                        5.2.5                h1de35cc_0
zlib                      1.2.11               h1de35cc_3

**Comment by ThilinaRajapakse** [comment]
Can you try running it with `use_multiprocessing` set to False?

**Comment by liubest** [comment]
Thanks. It works.
