### ISSUE TITLE
Error: Expected input batch_size (x) to match target batch_size (y)

### ISSUE THREAD

**Issue by antmarakis** [ThilinaRajapakse/simpletransformers#636]
Hi! I encountered an unexpected issue, maybe someone could help?

I am getting the following error when running my code (shown below):

```
Traceback (most recent call last):
  File "civil_eval.py", line 19, in <module>
    model.train_model(pd.DataFrame(train))
  File "/mounts/Users/cisintern/antmarakis/anaconda3/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 306, in train_model
    **kwargs,
  File "/mounts/Users/cisintern/antmarakis/anaconda3/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 474, in train
    outputs = model(**inputs)
  File "/mounts/Users/cisintern/antmarakis/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/mounts/Users/cisintern/antmarakis/anaconda3/lib/python3.7/site-packages/simpletransformers/classification/transformer_models/distilbert_model.py", line 64, in forward
    loss = loss_fct(logits.view(-1, self.num_labels), labels.view(-1))
  File "/mounts/Users/cisintern/antmarakis/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/mounts/Users/cisintern/antmarakis/anaconda3/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 932, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/mounts/Users/cisintern/antmarakis/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 2317, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/mounts/Users/cisintern/antmarakis/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 2113, in nll_loss
    .format(input.size(0), target.size(0)))
ValueError: Expected input batch_size (32) to match target batch_size (224).
```

**To Reproduce**

The data I use contains 8 columns. A text column and 7 floating point columns. The goal is to predict each floating point value (a regression problem).

My code is the following:

```
train = []
for i, r in train_df[:100000].iterrows():
    train.append([r['text'], [r['toxicity'], r['severe_toxicity'], r['obscene'], r['threat'], r['insult'], r['identity_attack'], r['sexual_explicit']]])

test = []
for i, r in test_df.iterrows():
    test.append([r['text'], [r['toxicity'], r['severe_toxicity'], r['obscene'], r['threat'], r['insult'], r['identity_attack'], r['sexual_explicit']]])


# Create a ClassificationModel
model = ClassificationModel('distilbert', 'distilbert-base-uncased', num_labels=7, args={'overwrite_output_dir': True, 'fp16': False, 'num_train_epochs': 1, 'regression': True, 'train_batch_size': 32})
model.train_model(pd.DataFrame(train))
```

**Further information**

I am running Ubuntu with the latest version of the library.

**Comment by ThilinaRajapakse** [comment]
Regression only works with a single target value at the moment. I.e. `num_labels` must be `1`. A possible workaround would be to have separate regression models for each label, but I realize that it may not be practical.

**Comment by antmarakis** [comment]
I see, that is alright!
