### ISSUE TITLE
Cannot import name 'amp' from 'torch.cuda'

### ISSUE THREAD

**Issue by kashesha** [ThilinaRajapakse/simpletransformers#717]
**Describe the bug**
wandb: WARNING W&B installed but not logged in.  Run `wandb login` or set the WANDB_API_KEY env variable.
100%|█████████████████████████████████████| 1807/1807 [00:00<00:00, 6444.58it/s]
Epoch:   0%|                                             | 0/20 [00:00<?, ?it/s]Traceback (most recent call last):
  File "finetune.py", line 35, in <module>
    model.train_model(train_df)
  File "/home/ubuntu/anaconda3/envs/transformers/lib/python3.8/site-packages/simpletransformers/classification/classification_model.py", line 321, in train_model
    global_step, tr_loss = self.train(
  File "/home/ubuntu/anaconda3/envs/transformers/lib/python3.8/site-packages/simpletransformers/classification/classification_model.py", line 468, in train
    from torch.cuda import amp
ImportError: cannot import name 'amp' from 'torch.cuda' (/home/ubuntu/anaconda3/envs/transformers/lib/python3.8/site-packages/torch/cuda/__init__.py)
Epoch:   0%| 

Not sure what this is about. I just upgraded my simpletransformers to the latest version.

**Comment by thiagosantos1** [comment]
There's a thread for this problem already:
https://github.com/ThilinaRajapakse/simpletransformers/issues/624
