### ISSUE TITLE
How to deal with the multiprocessing.pool.RemoteTraceback Error. 

### ISSUE THREAD

**Issue by non-swimmer** [ThilinaRajapakse/simpletransformers#73]
multiprocessing.pool.RemoteTraceback:    
assert len(label_ids) == max_seq_length
AssertionError
The above exception was the direct cause of the following exception:
    raise value
AssertionError

**Comment by ThilinaRajapakse** [comment]
Please provide steps to report the issue.

**Comment by bankreis** [comment]
Running into the same issue when adding my own dataset with other labels than the default CONLL2003 ones.

A minimal example reproducing it for me is:

`train = [[1, '1980', 'O'],
 [1, 'kam', 'O'],
 [1, 'der', 'O'],
 [1, 'Crown', 'B-OTH'],
 [1, 'als', 'O'],
 [1, 'Versuch', 'O'],
 [1, 'von', 'O'],
 [1, 'Toyota', 'B-ORG'],
 [1, ',', 'O'],
 [1, 'sich', 'O'],
 [1, 'in', 'O'],
 [1, 'der', 'O'],
 [1, 'Oberen', 'O'],
 [1, 'Mittelklasse', 'O'],
 [1, 'zu', 'O'],
 [1, 'etablieren', 'O'],
 [1, ',', 'O'],
 [1, 'auch', 'O'],
 [1, 'nach', 'O'],
 [1, 'Deutschland', 'B-LOC'],
 [1, '.', 'O'],
 [2, '–', 'O'],
 [2, '4:26', 'O'],
 [2, '#', 'O'],
 [2, 'Sometime', 'B-OTH'],
 [2, 'Ago/La', 'I-OTH'],
 [2, 'Fiesta', 'I-OTH']]

train_df = pd.DataFrame(train_data, columns=['sentence_id', 'words', 'labels'])

model = NERModel('bert', 'bert-base-cased', args={'fp16':False,'overwrite_output_dir': True, 'reprocess_input_data': True},labels=["O","B-LOC","I-LOC","B-ORG","I-ORG","B-PER","I-PER","B-OTH","I-OTH"])

model.train_model(train_df)`

**Comment by lecidhugo** [comment]
Hi @ThilinaRajapakse 
I faced the same problem above when attempting to train on NER task. The full stack of the exception is below:

Converting to features started.
  0%|                                                                    | 1/2200 [00:00<32:20,  1.13it/s]multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/pytorch_1/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/user/anaconda3/envs/pytorch_1/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/user/.local/lib/python3.6/site-packages/simpletransformers/ner/ner_utils.py", line 164, in convert_example_to_feature
    assert len(label_ids) == max_seq_length
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/2-projects/1-train-eavl-test.py", line 7, in <module>
    model.train_model('data/train.txt')
  File "/home/user/.local/lib/python3.6/site-packages/simpletransformers/ner/ner_model.py", line 160, in train_model
    train_dataset = self.load_and_cache_examples(train_data)
  File "/home/user/.local/lib/python3.6/site-packages/simpletransformers/ner/ner_model.py", line 538, in load_and_cache_examples
    silent=args['silent']
  File "/home/user/.local/lib/python3.6/site-packages/simpletransformers/ner/ner_utils.py", line 222, in convert_examples_to_features
    features = list(tqdm(p.imap(convert_example_to_feature, examples, chunksize=chunksize), total=len(examples), disable=silent))
  File "/home/user/.local/lib/python3.6/site-packages/tqdm/std.py", line 1087, in __iter__
    for obj in iterable:
  File "/home/user/anaconda3/envs/pytorch_1/lib/python3.6/multiprocessing/pool.py", line 320, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/home/user/anaconda3/envs/pytorch_1/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
AssertionError
  0%|                                                                    | 1/2200 [00:01<39:05,  1.07s/it]

**Comment by ThilinaRajapakse** [comment]
What does your data look like?

**Comment by lecidhugo** [comment]
It is a dataset in Arabic where each: <word> <space><label> is placed in a different line and an empty line between two sentences like the example of two sentences below:
بالاتحاد B-ORG
الدولي I-ORG
لكرة I-ORG
القدم I-ORG
) O
. O

الحرب B-MISC
العالمية I-MISC
الثانية I-MISC
). O

**Comment by lecidhugo** [comment]
Very weird that today the error vanished even though I made no modification to the code. That's good news but I am still wondering what would had caused the problem

**Comment by ThilinaRajapakse** [comment]
#97 Likely the same cause.
