### ISSUE TITLE
RoBERTa's  vocab file must a json file ?

### ISSUE THREAD

**Issue by MrRace** [ThilinaRajapakse/simpletransformers#733]
I use RoBERTa model for multi-label classification, when load the model's vocab file,  some errors come below：
```
Traceback (most recent call last):
  File "base_simpletransformers.py", line 262, in <module>
    args=train_args,
  File "/opt/conda/lib/python3.7/site-packages/simpletransformers/classification/multi_label_classification_model.py", line 171, in __init__
    self.tokenizer = tokenizer_class.from_pretrained(model_name, do_lower_case=self.args.do_lower_case, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1425, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1572, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/tokenization_roberta.py", line 171, in __init__
    **kwargs,
  File "/opt/conda/lib/python3.7/site-packages/transformers/tokenization_gpt2.py", line 169, in __init__
    self.encoder = json.load(vocab_handle)
  File "/opt/conda/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/opt/conda/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)

```
transformers Version: 3.2.0
simpletransformers Version：0.48.5
It seems mean the vocab should be a json file, and it can not load from a txt file. My raw vocab file is `vocab.txt`, I just rename it to `vocab.json`. How should I do to fix it? 
Best regards!

**Comment by ThilinaRajapakse** [comment]
Can you provide a minimal example? Roberta models work in multi-label classification for me without any issues.

**Comment by MrRace** [comment]
> Can you provide a minimal example? Roberta models work in multi-label classification for me without any issues.

As my pretrained RoBERTa model's vocab file is txt format, therefore I can not use the RobertaTokenizer directly. As RobertaTokenizer  need the vocab a json format. I change to choose the BertTokenizer and BertModel, and that can work !
