### ISSUE TITLE
Exception during training of ClassificationModel (in MultiProcessingDataLoaderIter)

### ISSUE THREAD

**Issue by aurik3l** [ThilinaRajapakse/simpletransformers#763]
**Describe the bug**
During the training of a classification model (at various stages / epochs), an exception occurs that is being ignored (afterwards, the training continues). It only seems to appear with a large enough number of training epochs (e.g., 15) and when evaluating the model during the training. Is this an expected behavior?

```
Epochs 5/15. Running Loss: 0.0001: 100%
1000/1000 [11:51<00:00, 1.41it/s]
100%
2000/2000 [09:37<00:00, 3.46it/s]
Exception ignored in: <bound method _MultiProcessingDataLoaderIter.__del__ of <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7fee7c735240>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1101, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1075, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 122, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
Exception ignored in: <bound method _MultiProcessingDataLoaderIter.__del__ of <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7fee7c241d68>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1101, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1075, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 122, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
Exception ignored in: <bound method _MultiProcessingDataLoaderIter.__del__ of <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7fee7dfd5c50>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1101, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1075, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 122, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
Exception ignored in: <bound method _MultiProcessingDataLoaderIter.__del__ of <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7fee459310f0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1101, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1075, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 122, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
```
In this run, the issue also appeared as part of epoch 12/15. When I retested it, it appeared during epochs 3/15 and 7/15.

**To Reproduce**
* Use the Colab example and use pip to install all prerequisites https://colab.research.google.com/drive/1Da833zWbDjYtE2a9PhzpqMdAfqUkXXLb?usp=sharing
* Restart the runtime
* Execute all other cells

**Additional context**
*  Google Colab (GPU-supported environment)
* simpletransformers            0.48.12 
* tensorflow                    2.3.0 
* torch                         1.6.0+cu101   
* transformers                  3.3.1

**Comment by ThilinaRajapakse** [comment]
Does this impact the trained model's performance?
