### ISSUE TITLE
T5 ERROR during restarting from a given checkpoint

### ISSUE THREAD

**Issue by sarapapi** [ThilinaRajapakse/simpletransformers#764]
**Describe the bug**
I'm trying to restart training from a given checkpoint, I've loaded the model using `model = T5Model("/PATHtoCHECKPOINT")` but the loss reset and starts from a higher value.
Inside the checkpoint folder, I have the 10 files: config.json, eval_results.txt, model_args.json, optimizer.pt, pytorch_model.bin, scheduler.pt, special_tokens_map.json, spiece.model, tokenizer_config.json, training_args.bin
Why this happening?
![W B Chart 21_10_2020, 14_56_37](https://user-images.githubusercontent.com/57095209/96722546-ccbadb80-13ad-11eb-9019-c3a4a817b67e.png)

EDIT:
If I keep the training going, at a certain step (not at the very beginning), the training stops and returns the error:
```
Traceback (most recent call last):
  File "TINIA_doubleTraining.py", line 112, in <module>
    model.train_model(train_df, eval_data=eval_df) #,args={'num_train_epochs': 5, 'learning_rate':2e-5})  #args=model_args, sacreBLEU=sacreBLEU)
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/simpletransformers/t5/t5_model.py", line 165, in train_model
    global_step, training_details = self.train(
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/simpletransformers/t5/t5_model.py", line 418, in train
    results = self.eval_model(
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/simpletransformers/t5/t5_model.py", line 613, in eval_model
    result = self.evaluate(eval_dataset, output_dir, verbose=verbose, silent=silent, **kwargs)
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/simpletransformers/t5/t5_model.py", line 673, in evaluate
    outputs = model(**inputs)
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 1 on device 5.
Original Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/datadrive/data/T5/transformers/src/transformers/modeling_t5.py", line 1169, in forward
    encoder_outputs = self.encoder(
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/datadrive/data/T5/transformers/src/transformers/modeling_t5.py", line 711, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 124, in forward
    return F.embedding(
  File "/home/ubuntu/anaconda3/envs/nlp_venv/lib/python3.8/site-packages/torch/nn/functional.py", line 1814, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: arguments are located on different GPUs at /opt/conda/conda-bld/pytorch_1595629395347/work/aten/src/THC/generic/THCTensorIndex.cu:403
```

**Expected behavior**
Load the model and continue the training starting from the given checkpoint

**Comment by ThilinaRajapakse** [comment]
Are you training on multiple GPUs?

**Comment by sarapapi** [comment]
@ThilinaRajapakse yes the error is given when the training is launched on multiple GPUs (in particular, 8 GPUs by AWS EC2), maybe it is due to the use of DataParallel, I don't know where the error is.
Moreover, the peaky loss is also thrown when using only one GPU, so it is a separate error.

**Comment by ThilinaRajapakse** [comment]
I do think it's related to DataParallel. Saving and loading from disk probably moves around some of the models/data leading to errors like this. Simple Transformers just uses the Huggingface `save_pretrained()` and `load_pretrained()` methods so I'm not sure what the exact cause is.

I've noticed the "peaky loss" behaviour as well, although it seems to resolve itself soon after. In general, I do try to avoid restarting training from checkpoints unless it is absolutely necessary (I know this is not a satisfactory solution!).

**Comment by sarapapi** [comment]
@ThilinaRajapakse do you suggest to open an issue on hugging face github? I've noticed that "something" is loaded on GPU 7 or 5 (randomly?), while the big amount of data is loaded on GPU 0 (default behavior).

About the peaky loss: this phenomena is not isolated, the peak is repeated after some steps then the "correct loss" is resumed and so on..
Maybe some gradient resets or something else that is not saved or loaded correctly?

**Comment by ThilinaRajapakse** [comment]
You can try opening an issue on HF, but I can't say for sure that it's a problem with their code. It's also possible that those two methods aren't intended for resuming training.

Probably something like that.

**Comment by sarapapi** [comment]
@ThilinaRajapakse I will try to open an issue an wait for their comment. Do you think that the peaky loss is also related to their save/load methods?

**Comment by ThilinaRajapakse** [comment]
I'm not sure tbh. 🤷🏼‍♂️
