### ISSUE TITLE
W&B error due to Sliding Window

### ISSUE THREAD

**Issue by Yannik1337** [ThilinaRajapakse/simpletransformers#788]
**Describe the bug**
Running Bert on text input with sliding window enabled leads to an error in W&B generating a ROC curve. Not using sliding window works fine (but yields lower results)

**Expected behavior**
Expected no error. 

**Desktop 
- running on Linux, with python 3.7, and simple transformer 0.48.14

**Additional context**
Traceback (most recent call last): 
  File ".../scripts/simpletransformer.py", line 70, in <module> 
    result, model_outputs, wrong_predictions = model.eval_model(test_df, acc=sklearn.metrics.accuracy_score, f1_macro=f1_func_macro, f1_micro=f1_func_micro) 
  File "/opt/conda/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 808, in eval_model 
    eval_df, output_dir, multi_label=multi_label, verbose=verbose, silent=silent, wandb_log=wandb_log, **kwargs 
  File "/opt/conda/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 974, in evaluate 
    wandb.log({"roc": wandb.plots.ROC(truth, model_outputs, labels_list)}) 
  File "/opt/conda/lib/python3.7/site-packages/wandb/plots/roc.py", line 73, in roc 
    return roc_table(fpr_dict, tpr_dict, classes, indices_to_plot) 
  File "/opt/conda/lib/python3.7/site-packages/wandb/plots/roc.py", line 52, in roc_table 
    fpr_dict[i], tpr_dict[i], _ = roc_curve(y_true, probas[:, i], 
IndexError: too many indices for array

**Comment by Yannik1337** [comment]
For those looking for a temporary fix: Remove any W&B arguments from the ClassificationArgs and log the metrics after training and evaluation is finished manually.
