### ISSUE TITLE
Fine tuning error

### ISSUE THREAD

**Issue by Artcs1** [ThilinaRajapakse/simpletransformers#875]
**Describe the bug**
I am trying to fine tune a language model using data from my domain. The data is written in text file with one example per line. However, train_model creates the following error:

**To Reproduce**

from simpletransformers.language_modeling import LanguageModelingModel
import logging

logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)

train_args = {
    "reprocess_input_data": True,
    "overwrite_output_dir": True,
    "num_train_epochs": 5,
}

model = LanguageModelingModel('bert', 'bert-base-cased', args=train_args, use_cuda = True)

model.train_model("raw/train.txt", eval_file="raw/val.txt")

model.eval_model("raw/test.txt")

**Screenshots**

Traceback (most recent call last):
  File "transfer_learning.py", line 17, in <module>
    model.train_model("raw/train.txt", eval_file="raw/val.txt")
  File "/home/jeffri/anaconda3/envs/curriculas/lib/python3.8/site-packages/simpletransformers/language_modeling/language_modeling_model.py", line 369, in train_model
    global_step, training_details = self.train(
  File "/home/jeffri/anaconda3/envs/curriculas/lib/python3.8/site-packages/simpletransformers/language_modeling/language_modeling_model.py", line 761, in train
    self.save_model(output_dir_current, optimizer, scheduler, model=model)
  File "/home/jeffri/anaconda3/envs/curriculas/lib/python3.8/site-packages/simpletransformers/language_modeling/language_modeling_model.py", line 1140, in save_model
    self.save_model_args(output_dir)
  File "/home/jeffri/anaconda3/envs/curriculas/lib/python3.8/site-packages/simpletransformers/language_modeling/language_modeling_model.py", line 1150, in save_model_args
    self.args.save(output_dir)
  File "/home/jeffri/anaconda3/envs/curriculas/lib/python3.8/site-packages/simpletransformers/config/model_args.py", line 101, in save
    json.dump(self.get_args_for_saving(), f)
  File "/home/jeffri/anaconda3/envs/curriculas/lib/python3.8/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/home/jeffri/anaconda3/envs/curriculas/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/jeffri/anaconda3/envs/curriculas/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/jeffri/anaconda3/envs/curriculas/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/jeffri/anaconda3/envs/curriculas/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
INFO:wandb.sdk.internal.internal:Internal process exited

**Comment by ShivamSharma1997** [comment]
Hey @Artcs1 , did you find the solution to this problem? I am also facing a similar problem when training a MultiLabelClassificationModel. 
This happened right after I updated the library. My error is listed bellow

Traceback (most recent call last):
  File "./scripts/TASK1/Text_Augmentation/Information_Type/cross_validation.py", line 54, in <module>
    preds,_ = model.predict(val_df['Text'])
  File "/home/s/ss4354/.local/lib/python3.7/site-packages/simpletransformers/classification/multi_label_classification_model.py", line 240, in predict
    return super().predict(to_predict, multi_label=multi_label)
  File "/home/s/ss4354/.local/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 1259, in predict
    if isinstance(to_predict[0], list):
  File "/home/s/ss4354/.local/lib/python3.7/site-packages/pandas/core/series.py", line 1071, in __getitem__
    result = self.index.get_value(self, key)
  File "/home/s/ss4354/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4730, in get_value
    return self._engine.get_value(s, k, tz=getattr(series.dtype, "tz", None))
  File "pandas/_libs/index.pyx", line 80, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 88, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 992, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 998, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 0
INFO:wandb.sdk.internal.internal:Internal process exited

**Comment by Artcs1** [comment]
Hi Shivam,

I rebuild my environment with python3.6.10, and simpletransformers 0.49.2,
transformers 3.5.1, and that solves the problem for me. Sorry for the late
response hope you can solve it.

Greetings,
Jeffri
