### ISSUE TITLE
dataloader: 'dict' object has no attribute 'size'

### ISSUE THREAD

**Issue by mattivi** [ThilinaRajapakse/simpletransformers#895]
**Describe the bug**
I get the following error when having dataset type set to 'line_by_line'.  Dataset size is 1M rows.

Parameters related to dataset:
```
{'dataset_type': 'line_by_line', 
'reprocess_input_data': True, 
'clean_text': False, 
'vocab_size': 30000, 
'min_frequency': 1, 
'max_seq_length': 16,
'dataloader_num_workers': 3,
'process_count': 3}
```
- `simpletransformers` version: 0.51.3
- `tokenizers` version: 0.9.4 
- `transformers` version: 4.1.0.dev0
- Python version: Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
- PyTorch version: 1.7.1

**Screenshots**
```
[00:00:25] Reading files (67 Mo)                    ███████████████████████████████                 100
[00:00:00] Tokenize words                           █████████████████████████████████ 33239    /    33239
[00:00:23] Count pairs                              █████████████████████████████████ 33239    /    33239
[00:00:00] Compute merges                           █████████████████████████████████ 29922    /    29922

INFO:simpletransformers.language_modeling.language_modeling_model: Training of None tokenizer complete. Saved to /mapr/projects/opp/CLM/PSM/models/clm-bert-base-v2/.
INFO:simpletransformers.language_modeling.language_modeling_model: Training language model from scratch
/home/user/conda/lib/python3.7/site-packages/transformers/data/datasets/language_modeling.py:128: 
FutureWarning: This dataset will be removed from the library soon, preprocessing should be handled with the 🤗 Datasets library. 
You can have a look at this example script for pointers: https://github.com/huggingface/transformers/blob/master/examples/language-modeling/run_mlm.py
  FutureWarning,

INFO:simpletransformers.language_modeling.language_modeling_model: Training started
Epoch:   0%|                                               | 0/2 [00:00<?, ?it/s]wandb: 

Running Epoch 0 of 2:   0%|                                      | 0/1954 [00:00<?, ?it/s]]
Epoch 1 of 2:   0%|                                   | 0/2 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "run_train_electra.py", line 122, in <module>
    model.train_model(train_file=train_files[0], eval_file=eval_files[0])
  File "/home/user/conda/lib/python3.7/site-packages/simpletransformers/language_modeling/language_modeling_model.py", line 382, in train_model
    **kwargs,
  File "/home/user/conda/lib/python3.7/site-packages/simpletransformers/language_modeling/language_modeling_model.py", line 627, in train
    for step, batch in enumerate(batch_iterator):
  File "/home/user/conda/lib/python3.7/site-packages/tqdm/std.py", line 1167, in __iter__
    for obj in iterable:
  File "/home/user/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/user/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/user/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/user/conda/lib/python3.7/site-packages/simpletransformers/language_modeling/language_modeling_model.py", line 415, in collate
    return pad_sequence(examples, batch_first=True, padding_value=tokenizer.pad_token_id)
  File "/home/user/conda/lib/python3.7/site-packages/torch/nn/utils/rnn.py", line 358, in pad_sequence
    max_size = sequences[0].size()
AttributeError: 'dict' object has no attribute 'size'
```

**Comment by ThilinaRajapakse** [comment]
The underlying Hugging Face tokenizers have changed so this dataset type no longer works. It'll probably need to be depreceated.
