### ISSUE TITLE
current_loss = loss.item()     649      650                 if show_running_loss:  RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Deep-learning999** [ThilinaRajapakse/simpletransformers#904]
# Create a ClassificationModel
model = ClassificationModel(
    "xlnet", "pre_model", args=train_args,num_labels=3
,use_cuda=cuda_available)
# Train the model
model.train_model(train_df)

current_loss = loss.item()
    649 
    650                 if show_running_loss:

RuntimeError: CUDA error: device-side assert triggered

**Comment by Chokerino** [comment]
Im getting the same error. I trained a langauge model first with the following code 

```
cuda_available = torch.cuda.is_available()
    logging.basicConfig(level=logging.INFO)
    transformers_logger = logging.getLogger("transformers")
    transformers_logger.setLevel(logging.WARNING)
    print(cuda_available)
    
    #cuda_available = False
    train_args = {
        "reprocess_input_data": True,
        "overwrite_output_dir": True,
        "vocab_size": 10000,
    }
    
    model = LanguageModelingModel('electra', None, args=train_args, train_files="bert_data_train.txt",use_cuda=cuda_available)
    
    model.train_model("bert_data_train.txt", eval_file="bert_data_test.txt")
    
    model.eval_model("bert_data_test.txt")
```

and then was fine tuned using 

```
logging.basicConfig(level=logging.INFO)
    transformers_logger = logging.getLogger("transformers")
    transformers_logger.setLevel(logging.WARNING)
    labels=[0,1]
    train_args = {
    "output_dir": "ner_output",
    "overwrite_output_dir": True,
    }
    #train_file = "btest.csv"
    train_file = pd.read_csv("btest.csv")
    train_file=train_file.astype({train_file.columns[1]:int})
    model = ClassificationModel("electra", "outputs/discriminator_model", num_labels=2,args=train_args)
    model.train_model(train_file)

# Evaluate the model
    result, model_outputs, predictions = model.eval_model(train_file)
    print(result)
````

and the stack trace 
```
Traceback (most recent call last):
  File "testing.py", line 22, in <module>
    model.train_model(train_file)
  File "D:\Anaconda\envs\myenv\lib\site-packages\simpletransformers\classification\classification_model.py", line 397, in train_model
    global_step, training_details = self.train(
  File "D:\Anaconda\envs\myenv\lib\site-packages\simpletransformers\classification\classification_model.py", line 584, in train
    current_loss = loss.item()
RuntimeError: CUDA error: device-side assert triggered
INFO:wandb.sdk.internal.internal:Internal process exited
```

**Comment by Chokerino** [comment]
I had a similar issue and it was because i had negative value in the labels.
