### ISSUE TITLE
KeyError in T5model

### ISSUE THREAD

**Issue by VictoryDong** [ThilinaRajapakse/simpletransformers#962]
**Describe the bug**
I plan to use T5model for simple training, but it doesn’t work.

codes:
```
from simpletransformers.t5 import T5Model ,T5Args
from pandas import DataFrame

if __name__ == '__main__':
    model_args = T5Args()
    model = T5Model('t5', "t5-small", args=model_args, use_cuda=False)
    trainset=[["gec","I is a good boy.","I am a good boy ."],["gec","hello, I'm kitty.","Hello, I'm Kitty."]]
    df=DataFrame(trainset)
    df.columns = ["prefix","input_text", "target_text"]
    model.train(df,"output_folder")
```

exception:
```
Traceback (most recent call last):
  File "....venv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 68, in <module>
    model.train(df,model_args.output_dir)
  File "venv/lib/python3.8/site-packages/simpletransformers/t5/t5_model.py", line 433, in train
    for step, batch in enumerate(batch_iterator):
  File "venv/lib/python3.8/site-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "venv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 1

```
lib version:
* simpletransformers== 0.51.13
* transformers==4.0.1
* pandas==1.2.0
* tqdm==4.47.0\4.56.0(both version do not work)
* torch==1.7.1

**Comment by VictoryDong** [comment]
use train_model
