### ISSUE TITLE
model.eval_model(eval_df) not working

### ISSUE THREAD

**Issue by timpal0l** [ThilinaRajapakse/simpletransformers#984]
**Describe the bug**
Cannot perform model evaluation using `model.eval_model(eval_df)` during simple binary text classification.

**To Reproduce**

```
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score

from simpletransformers.classification import ClassificationModel

df = pd.read_csv('/home/sentiment.csv')

train_df = pd.DataFrame(df[0:8000])
eval_df = pd.DataFrame(df[8000:])

train_args = {
    'reprocess_input_data': True,
    'overwrite_output_dir': True,
#    'evaluate_during_training': True,
    'max_seq_length': 128,
    'num_train_epochs': 1,
#    'evaluate_during_training_steps': 100,
    'train_batch_size': 64,
    'n_gpu': 1,
}

model_name = "ltgoslo/norbert"

model = ClassificationModel('bert', model_name, args=train_args, cuda_device=1)
model.train_model(train_df)
result, model_outputs, wrong_predictions = model.eval_model(eval_df)
```

**Expected behavior**
`model.eval_model(eval_df)`should report metrics.

**Error**
```
/home/tim/anaconda3/envs/transformers-source/lib/python3.7/site-packages/sklearn/metrics/_classification.py:870: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
Traceback (most recent call last):
  File "eval_sent.py", line 28, in <module>
    result, model_outputs, wrong_predictions = model.eval_model(eval_df)
  File "/home/tim/anaconda3/envs/transformers-source/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 911, in eval_model
    eval_df, output_dir, multi_label=multi_label, verbose=verbose, silent=silent, wandb_log=wandb_log, **kwargs
  File "/home/tim/anaconda3/envs/transformers-source/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 1079, in evaluate
    result, wrong = self.compute_metrics(preds, model_outputs, out_label_ids, eval_examples, **kwargs)
  File "/home/tim/anaconda3/envs/transformers-source/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 1285, in compute_metrics
    fpr, tpr, thresholds = roc_curve(labels, scores)
  File "/home/tim/anaconda3/envs/transformers-source/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/tim/anaconda3/envs/transformers-source/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 914, in roc_curve
    y_true, y_score, pos_label=pos_label, sample_weight=sample_weight)
  File "/home/tim/anaconda3/envs/transformers-source/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 697, in _binary_clf_curve
    assert_all_finite(y_score)
  File "/home/tim/anaconda3/envs/transformers-source/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/tim/anaconda3/envs/transformers-source/lib/python3.7/site-packages/sklearn/utils/validation.py", line 124, in assert_all_finite
    _assert_all_finite(X.data if sp.issparse(X) else X, allow_nan)
  File "/home/tim/anaconda3/envs/transformers-source/lib/python3.7/site-packages/sklearn/utils/validation.py", line 106, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```
**Desktop (please complete the following information):**
 - Ubuntu 20.04, CUDA Version: 11.0, GeForce GTX Titan X

**Comment by ThilinaRajapakse** [comment]
Is there any difference between the standard BERT architecture and norbert?
